---
- name: "Docker login {{ docker_registry }}"
  docker_login:
    registry_url: "https://{{ docker_registry }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
    tls: true
    tls_hostname: "{{ docker_registry }}"

- name: "Pull image {{ antispam_image }}"
  docker_image:
    name: "{{ docker_registry }}/{{ antispam_image }}:{{ antispam_ver }}"
    source: pull
    force_source: true

- name: "Run container {{ antispam_image | split('/') | last }}"
  docker_container:
    detach: true
    state: started
    name: "{{ antispam_image | split('/') | last }}"
    image: "{{ docker_registry }}/{{ antispam_image }}:{{ antispam_ver }}"
    restart_policy: unless-stopped
    ports:
      - 8001:8000

- name: Prune old images
  docker_prune:
    images: true
