{
 "title": "CRM-project availability metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "target",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CRM  Site  Endpoints  metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"$target\", job=\"availability_api_metabuild\"}   ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"$target\", job=\"availability_api_metabuild\"}   "
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site availability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"$target\", job=\"availability_api_metabuild\"}   ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Probe HTTP duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"$target\", job=\"availability_api_metabuild\",phase=\"connect\"}",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "probe_http_duration_seconds{instance=\"$target\", job=\"availability_api_metabuild\",phase=\"processing\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"$target\", job=\"availability_api_metabuild\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}