{
 "title": "Beanstalkd",
 "description": "Beanstalk",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(beanstalkd_exporter_requests_total{job=\"beanstalk_crm\"}, name)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(current_tubes{env=~\"$env\",job=~\"beanstalk_crm\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Beanstalkd uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "current_tubes{env=~\"$env\",job=~\"beanstalk_crm\"}"
    }
   ]
  },
  {
   "title": "Host name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_tubes{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Workers/Producers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Number of tubes/producers/workers/waiting",
   "type": "graph",
   "description": "tubes -  the number of currently-existing tubes\n\nproducers - the number of open connections that have each issued at least one put command\n\nworkers - the number of open connections that have each issued at least one reserve command\n\nwaiting - the number of open connections that have issued a reserve command but not yet received a response\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "current_tubes{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "tubes"
    },
    {
     "expr": "current_workers{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "workers"
    },
    {
     "expr": "current_producers{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "producers"
    },
    {
     "expr": "current_waiting{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "waiting"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Job Total",
   "type": "graph",
   "description": "Cumulative count of jobs created in all tubes after restart beanstalkd process  in rate of range 1 minutes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(total_jobs{env=~\"$env\",job=~\"beanstalk_crm\"}[1m])",
     "legendFormat": "jobs total"
    }
   ]
  },
  {
   "title": "Jobs count",
   "type": "graph",
   "description": "Current number jobs in different state",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "current_jobs_ready{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "ready"
    },
    {
     "expr": "current_jobs_buried{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "buried"
    },
    {
     "expr": "current_jobs_delayed{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "delayed"
    },
    {
     "expr": "current_jobs_reserved{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "reserved"
    },
    {
     "expr": "current_jobs_urgent{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "urgent"
    }
   ]
  },
  {
   "title": "Tube total jobs count - absolute value",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,tube) (tube_total_jobs{env=~\"$env\",job=~\"beanstalk_crm\"})",
     "legendFormat": "{{ tube }}"
    }
   ]
  },
  { "title": "Tube", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Tube total jobs count",
   "type": "graph",
   "description": "Tube total jobs in rate of range 1 minutes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,tube) (irate(tube_total_jobs{env=~\"$env\",job=~\"beanstalk_crm\"}[1m]))",
     "legendFormat": "{{ tube }}"
    }
   ]
  },
  {
   "title": "Tube current jobs READY - absolute value",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,tube) (tube_current_jobs_ready{env=~\"$env\",job=~\"beanstalk_crm\"})",
     "legendFormat": "{{ tube }}"
    }
   ]
  },
  {
   "title": "Tube current jobs RESERVED - absolute value",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,tube) (tube_current_jobs_reserved{env=~\"$env\",job=~\"beanstalk_crm\"})",
     "legendFormat": "{{ tube }}"
    }
   ]
  },
  {
   "title": "Tube current jobs DELAYED - absolute value",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,tube) (tube_current_jobs_delayed{env=~\"$env\",job=~\"beanstalk_crm\"})",
     "legendFormat": "{{ tube }}"
    }
   ]
  },
  {
   "title": "Tube current jobs BURIED - absolute value",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,tube) (tube_current_jobs_buried{env=~\"$env\",job=~\"beanstalk_crm\"})",
     "legendFormat": "{{ tube }}"
    }
   ]
  },
  {
   "title": "Tube current jobs URGENT - absolute value",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,tube) (tube_current_jobs_urgent{env=~\"$env\",job=~\"beanstalk_crm\"})",
     "legendFormat": "{{ tube }}"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Commands/s with range of 5 minutes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(cmd_delete{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "irate(cmd_ignore{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "ignore"
    },
    {
     "expr": "irate(cmd_put{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "irate(cmd_reserve_with_timeout{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "reserve_with_timeout"
    },
    {
     "expr": "irate(cmd_stats{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "stats"
    },
    {
     "expr": "irate(cmd_stats_job{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "stats_job"
    },
    {
     "expr": "irate(cmd_stats_tube{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "stats_tube"
    },
    {
     "expr": "irate(cmd_use{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "use"
    },
    {
     "expr": "irate(cmd_watch{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "watch"
    },
    {
     "expr": "irate(cmd_reserve{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "reserve"
    },
    {
     "expr": "irate(cmd_bury{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "bury"
    },
    {
     "expr": "irate(cmd_kick{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "kick"
    },
    {
     "expr": "irate(cmd_pause_tube{env=~\"$env\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "pause_tube"
    },
    {
     "expr": "irate(cmd_release{name=~\"$node\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "release"
    },
    {
     "expr": "irate(cmd_list_tubes{name=~\"$node\",job=~\"beanstalk_crm\"}[5m])",
     "legendFormat": "list_tubes"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Total connections",
   "type": "graph",
   "description": "Total  count of connections in rate of range 1 minutes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(total_connections{env=~\"$env\",job=~\"beanstalk_crm\"}[1m])",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Binlog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true
  },
  {
   "title": "Binlog current index",
   "type": "graph",
   "description": "Index of the current binlog file ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "binlog_current_index{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "current_index"
    }
   ]
  },
  {
   "title": "Binlog oldest index",
   "type": "graph",
   "description": "The index of the oldest binlog file needed to store the current jobs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "binlog_oldest_index{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "oldest_index"
    }
   ]
  },
  {
   "title": "Binlog max size",
   "type": "graph",
   "description": "The maximum size in bytes a binlog file is allowed to get before a new binlog file is opened",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "binlog_max_size{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "binlog_max_size"
    }
   ]
  },
  {
   "title": "Binlog records written - absolute value",
   "type": "graph",
   "description": "the cumulative number of records written to the binlog ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "binlog_records_written{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "binlog_records_written"
    }
   ]
  },
  {
   "title": "Binlog records written",
   "type": "graph",
   "description": "the  number of records written to the binlog in rate of  range 1 minutes",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(binlog_records_written{env=~\"$env\",job=~\"beanstalk_crm\"}[1m])",
     "legendFormat": "binlog_records_written"
    }
   ]
  },
  {
   "title": "Binlog records migrated",
   "type": "graph",
   "description": "The cumulative number of records written as part of compaction",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "binlog_records_migrated{env=~\"$env\",job=~\"beanstalk_crm\"}",
     "legendFormat": "binlog_max_size"
    }
   ]
  }
 ]
}