{
 "title": "Centrifugo",
 "description": "https://centrifugal.github.io/centrifugo/",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "quantile", "label": "Quantile", "query": "0.5,0.99,0.999" },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({__name__=~\"centrifugo_.*\"}, name)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(centrifugo_node_build,  version)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "insrance",
    "label": "instance",
    "query": {
     "query": "label_values(process_start_time_seconds{env=~\"$env\",project=\"crm\",job=~\"centrifugo_.*\"}, instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(process_start_time_seconds{env=\"$env\",project=\"crm\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Centrifugo $version",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center;\">\n<img src=\"https://centrifugal.github.io/centrifugo/images/favicon.png\" width=\"100\">\n</p>"
   }
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{env=~\"$env\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{env=~\"$env\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Total client connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(centrifugo_node_num_clients{env=~\"$env\", job=\"$job\"})",
     "legendFormat": "-"
    }
   ]
  },
  {
   "title": "Num nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(centrifugo_node_num_nodes{env=~\"$env\", job=\"$job\"})",
     "legendFormat": "-"
    }
   ]
  },
  {
   "title": "Host name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{env=~\"$env\", job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Client command count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_client_command_duration_seconds_count{env=~\"$env\", job=\"$job\"}[2m])*60)) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Client command time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(centrifugo_client_command_duration_seconds{quantile=\"$quantile\", job=~\"$job\",env=~\"$env\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API command count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_api_command_duration_seconds_count{env=~\"$env\"}[2m])*60)) by (protocol, method)",
     "legendFormat": "{{protocol}}://{{method}}"
    }
   ]
  },
  {
   "title": "API command time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(centrifugo_api_command_duration_seconds{quantile=\"$quantile\", env=~\"$env\",job=\"$job\"}) by (protocol, method)",
     "legendFormat": "{{protocol}}://{{method}}"
    }
   ]
  },
  {
   "title": "Num client connections per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "centrifugo_node_num_clients{env=~\"$env\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Num unique users per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "centrifugo_node_num_users{env=~\"$env\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Num unique channels per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "centrifugo_node_num_channels{env=~\"$env\", job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Node messages sent count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_node_messages_sent_count{env=~\"$env\",job=\"$job\"}[2m])*60)) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Node messages received count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(centrifugo_node_messages_received_count{env=~\"$env\",job=\"$job\"}[2m])*60) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Transport total messages sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(centrifugo_transport_messages_sent{env=~\"$env\",job=\"$job\"}[2m])*60) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Transport connection rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_transport_connect_count{env=~\"$env\",job=\"$job\"}[2m])*60)) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Disconnect by server count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_client_num_server_disconnects{env=~\"$env\",job=\"$job\"}[2m])*60)) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Node action count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_node_action_count{env=~\"$env\", job=\"$job\"}[2m])*60)) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Proxy calls count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_proxy_duration_seconds_count{env=~\"$env\"}[2m])*60)) by (protocol, type)",
     "legendFormat": "{{protocol}}://{{type}}"
    }
   ]
  },
  {
   "title": "Proxy call errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(rate(centrifugo_proxy_errors{env=~\"$env\"}[2m])*60)) by (protocol, type)",
     "legendFormat": "{{protocol}}://{{type}}"
    }
   ]
  },
  {
   "title": "Proxy calls time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(centrifugo_proxy_duration_seconds{quantile=\"$quantile\", env=~\"$env\"}) by (protocol, type)",
     "legendFormat": "{{protocol}}://{{type}}"
    }
   ]
  },
  {
   "title": "Go goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{env=~\"$env\", job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Go GC duration 0.75 quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\", env=~\"$env\", job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process open file descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{env=~\"$env\", job=\"$job\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "process_max_fds{env=~\"$env\", job=\"$job\"}",
     "legendFormat": "max:{{name}}"
    }
   ]
  },
  {
   "title": "Process OS threads created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{env=~\"$env\", job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process resident memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{env=~\"$env\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{env=~\"$env\", job=\"$job\"}[5m])*100",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}