{
 "title": "Health Checks",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "https://api.crm.dev.travel-dev.com",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://api.crm.dev.travel-dev.com\", job=\"availability_api_metabuild\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "https://crm.dev.travel-dev.com",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://crm.dev.travel-dev.com\", job=\"availability_api_metabuild\"}  ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "https://ws.crm.dev.travel-dev.com",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://ws.crm.dev.travel-dev.com\", job=\"availability_api_metabuild\"}   ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "https://centrifugo.crm.dev.travel-dev.com/health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://centrifugo.crm.dev.travel-dev.com/health\", job=\"availability_api_metabuild\"}   ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Beanstalkd",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_tubes{env=~\"$env\",job=~\"beanstalk_crm\"}"
    }
   ]
  },
  {
   "title": "Centrifugo",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{env=~\"$env\", job=\"centrifugo_crm\"})"
    }
   ]
  },
  {
   "title": "PHP PFM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "phpfpm_up{project=\"crm\", job=\"phpfpm_crm\", env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{project=\"crm\", env=~\"$env\", job=\"redis_crm\"} "
    }
   ]
  },
  {
   "title": "Supervisord",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_supervisord_up{env=~\"$env\", instance=~\".*\", name=~\".*crm.*\"}) by (name, instance)"
    }
   ]
  }
 ]
}