{
 "title": "CRM dynamic scheme",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CRM  Project",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 21, "w": 18, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_up{instance=~\".*\", project=\"crm\", job=\"redis_crm\", env=~\"$env\"} "
    },
    {
     "expr": "phpfpm_up{project=\"crm\", job=\"phpfpm_crm\", env=~\"$env\"}"
    },
    {
     "expr": "probe_success{env=~\"$env\"}"
    },
    {
     "expr": "node_scrape_collector_success{name=~\"^app0.*\", collector=\"supervisord\", env=\"$env\"}"
    }
   ]
  },
  {
   "title": "LB activ connections",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Active Connections",
     "dimensions": {
      "LoadBalancer": "app/app-crm-dev/608dcc474847ffc6"
     },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "LB new connections",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/app-crm-dev/608dcc474847ffc6"
     },
     "metricName": "NewConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "LB HTTP 5XX",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "HTTP 5XX",
     "dimensions": {
      "LoadBalancer": "app/app-crm-dev/608dcc474847ffc6"
     },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}