{
 "title": "PHP",
 "description": "PHP-FPM monitoring dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(node_exporter_build_info, ns)"
    }
   },
   {
    "name": "env",
    "query": {
     "query": "label_values(node_exporter_build_info{ns=~\"$namespace\"},env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(phpfpm_up{project=\"crm\", env=\"$env\",ns=~\"$namespace\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "phpfpm_up{project=\"crm\", env=\"$env\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Host name",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "phpfpm_up{project=\"crm\", env=~\"$env\", instance=\"$instance\"} ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "graph",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_accepted_connections_total{project=\"crm\", env=\"$env\", instance=\"$instance\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Max Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_active_max_processes{project=\"crm\", env=\"$env\", instance=\"$instance\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Listen Queue Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue_connections{env=\"$env\", project=\"crm\", instance=\"$instance\"})by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Listen Queue Length Connections",
   "type": "graph",
   "description": "The length of the socket queue, dictating maximum number of pending connections",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(phpfpm_listen_queue_length_connections{env=\"$env\", project=\"crm\", instance=\"$instance\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Listen Queue Max Connections",
   "type": "graph",
   "description": "Max number of connections the listen queue has reached since FPM start",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue_max_connections{env=\"$env\", project=\"crm\", instance=\"$instance\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Children Reached",
   "type": "graph",
   "description": "Number of times the process limit has been reached",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_max_children_reached_total{env=\"$env\", project=\"crm\", instance=\"$instance\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_processes_total{env=\"$env\", project=\"crm\", instance=\"$instance\"}) by (name, state)",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "graph",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_slow_requests_total{env=\"$env\", project=\"crm\", instance=\"$instance\"}) by (name)",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  }
 ]
}