{
 "title": "Status page",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(node_exporter_build_info, ns)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(node_exporter_build_info{ns=~\"$namespace\"},env)"
    }
   },
   {
    "name": "shared_instance",
    "label": "instance",
    "query": {
     "query": "label_values(redis_up{ project=\"crm\", env=~\"$env\", job=~\"crm_redis.*\",ns=~\"$namespace\"} ,instance)"
    }
   },
   {
    "name": "app_target",
    "query": {
     "query": "label_values(probe_success{env=\"$env\",ns=~\"$namespace\"}, instance)"
    }
   },
   {
    "name": "api_target",
    "query": {
     "query": "label_values(probe_success{env=\"$env\",ns=~\"$namespace\"}, instance)"
    }
   },
   {
    "name": "app_instance",
    "label": "instance",
    "query": {
     "query": "label_values(phpfpm_up{project=\"crm\", job=~\"crm_phpfpm.*\", env=\"$env\",ns=~\"$namespace\"},instance)"
    }
   },
   {
    "name": "loadbalancer",
    "label": "Load Balancer",
    "query": {}
   },
   {
    "name": "dbinstanceidentifier_pgsql",
    "label": "DBInstanceIdentifier",
    "query": {}
   },
   {
    "name": "ws_target",
    "query": {
     "query": "label_values(probe_success{env=\"$env\",ns=~\"$namespace\"}, instance)"
    }
   },
   {
    "name": "centrifugo_target",
    "query": {
     "query": "label_values(probe_success{env=\"$env\",ns=~\"$namespace\"}, instance)"
    }
   },
   {
    "name": "dbinstanceidentifier_mysql",
    "label": "DBInstanceIdentifier",
    "query": {}
   },
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region" }
  ]
 },
 "panels": [
  {
   "title": "ALB",
   "type": "stat",
   "description": "ActiveConnectionCount sum",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "App",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$app_target\", env=~\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$api_target\", env=~\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$ws_target\", env=~\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Centrifugo",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$centrifugo_target\", env=~\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PHP PFM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "phpfpm_up{project=\"crm\", job=~\"crm_phpfpm.*\", env=\"$env\",ns=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Supervisord",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_supervisord_up{env=~\"$env\", name=~\".*crm.*\",ns=~\"$namespace\"}) by (name, instance)"
    }
   ]
  },
  {
   "title": "Beanstalkd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_tubes{env=~\"$env\",job=~\"crm_beanstalk.*\",ns=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{project=\"crm\", env=~\"$env\", job=~\"crm_redis.*\",ns=~\"$namespace\"} "
    }
   ]
  },
  {
   "title": "Centrifugo",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{env=~\"$env\",instance=\"$shared_instance\", job=~\"crm_centrifugo.*\"}"
    }
   ]
  },
  {
   "title": "PGSQL",
   "type": "stat",
   "description": "Database connections max",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier_pgsql" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "description": "Database connections max",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier_mysql" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}