{
 "title": "Sticky Tables",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": { "query": "label_values(haproxy_up, name)" } }
  ]
 },
 "panels": [
  {
   "title": "Total req from IP to CRM Backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_stick_table_key_http_req_total{key=~\".+\", name=\"$host\", table=\"crm_backend\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total req from IP to CRM API Backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_stick_table_key_http_req_total{key=~\".+\", name=\"$host\", table=\"crm_api_backend\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total WS Requests from User ID",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_stick_table_key_http_req_total{key=~\".+\", name=\"$host\", table=\"ws_backend\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Req rate over 1 min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_stick_table_key_http_req_rate{key=~\".+\", period=~\"60000\", name=\"$host\", table=~\".*\"}",
       "legendFormat": "{{key}} - {{table}}"
      }
     ]
    },
    {
     "title": "Req total ws_backend",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(haproxy_stick_table_key_http_req_total{key=~\".+\", name=~\"$host\", table=~\"ws_backend\"}) by (key, table)",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Req total crm_backend",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(haproxy_stick_table_key_http_req_total{key=~\".+\", name=~\"$host\", table=\"crm_backend\"}) by (key)",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Req total crm_api_backend",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(haproxy_stick_table_key_http_req_total{key=~\".+\", name=~\"$host\", table=~\"crm_api_backend\"}) by (key)",
       "legendFormat": "{{key}}"
      }
     ]
    }
   ]
  }
 ]
}