{
 "title": "Supervisord",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_supervisord_up{env=~\"$env\",  name=~\".*crm.*\"},instance) "
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_supervisord_up{env=\"$env\",project=\"crm\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_supervisord_up{env=~\"$env\", instance=~\"$instance\", name=~\".*crm.*\"}) by (name, instance)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "supervisor job up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_supervisord_up{env=~\"$env\", instance=~\"$instance\", name=~\".*crm.*\"}) by (name, instance)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Host name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_supervisord_up{env=~\"$env\", instance=~\"$instance\", name=~\".*crm.*\"}) by (name, instance)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "supervisor restarts / 5 min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(node_supervisord_start_time_seconds{env=\"$env\",instance=\"$instance\", project=\"crm\", job=\"$job\"}[5m])",
     "legendFormat": "{{name}} - {{exported_name}}"
    }
   ]
  },
  {
   "title": "supervisor job state",
   "type": "graph",
   "description": "Process States\n--------------\n0=STOPPED, 10=STARTING,\n20=RUNNING, 30=BACKOFF,\n40=STOPPING, 100=EXITED,\n200=FATAL, 1000=UNKNOWN",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_supervisord_state{env=~\"$env\", job=\"$job\",instance=\"$instance\", name=~\".*crm.*\"}",
     "legendFormat": "{{name}} - {{exported_name}}"
    }
   ]
  }
 ]
}