---
- name: Install redis
  apt:
    name: redis
    state: present

- name: Configure redis
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: 0644
  notify: restart redis

- name: Ensure redis is started
  systemd:
    name: redis
    state: started
    enabled: true
