path: ./
jobs: 10
cache: .phplint.cache
extensions:
  - php
exclude:
  - vendor
  - node_modules
  - docker
  - common/tests
  - common/runtime
  - frontend/runtime
  - frontend/tests
  - frontend/web
  - webapi/runtime
  - webapi/tests
  - webapi/web
  - console/migrations
warning: false