<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2022-04-18 13:03:58
 */
return [
    'AllSharedAsset' => [
        'class' => 'frontend\\assets\\groups\\AllSharedAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'all-shared.min.js',
        ],
        'css' => [
            'all-shared.min.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'AllSharedGroupAsset' => [
        'class' => 'frontend\\assets\\groups\\AllSharedGroupAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'all-shared-group.min.js',
        ],
        'css' => [
            'all-shared-group.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'FontAwesomeAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAsset',
        'basePath' => '@webroot/fontawesome/build',
        'baseUrl' => '@web/fontawesome/build',
        'js' => '',
        'css' => '',
        'depends' => [],
        'sourcePath' => null,
    ],
    'GlyphiconAsset' => [
        'class' => 'kivork\\bootstrap4glyphicons\\assets\\GlyphiconAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'glyphicon.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'PageLoaderAsset' => [
        'class' => 'frontend\\assets\\PageLoaderAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'page-loader.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'GentelellaGroupAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaGroupAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'gentelella.min.js',
        ],
        'css' => [
            'gentelella.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'GentelellaCrudGroupAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaCrudGroupAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'gentelella-crud-group.min.js',
        ],
        'css' => [
            'gentelella-crud-group.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'NotificationSocketAsset' => [
        'class' => 'frontend\\widgets\\notification\\NotificationSocketAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'notification-socket.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'CentrifugeAsset' => [
        'class' => 'frontend\\assets\\CentrifugeAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'centrifuge.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ClientChatWidgetAsset' => [
        'class' => 'frontend\\widgets\\clientChat\\ClientChatWidgetAsset',
        'basePath' => '@webroot/client_chat/build',
        'baseUrl' => '@web/client_chat/build',
        'js' => [
            'client_chat_widget.min.js',
        ],
        'css' => [
            'client_chat_widget.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ClientChatAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\ClientChatAsset',
        'basePath' => '@webroot/client_chat/build',
        'baseUrl' => '@web/client_chat/build',
        'js' => [
            'client_chat.min.js',
        ],
        'css' => [
            'client_chat.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'CallBoxAsset' => [
        'class' => 'frontend\\assets\\CallBoxAsset',
        'basePath' => '@webroot/client_chat/build',
        'baseUrl' => '@web/client_chat/build',
        'js' => [
            'call_box.min.js',
        ],
        'css' => [
            'call_box.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'EditToolAsset' => [
        'class' => 'frontend\\assets\\EditToolAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'edit_tool.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'NewWebPhoneAsset' => [
        'class' => 'frontend\\widgets\\newWebPhone\\NewWebPhoneAsset',
        'basePath' => '@webroot/web_phone/build',
        'baseUrl' => '@web/web_phone/build',
        'js' => [
            'web_phone.min.3.46.1.js',
        ],
        'css' => [
            'web_phone.min.3.46.1.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'DeviceAsset' => [
        'class' => 'frontend\\widgets\\newWebPhone\\DeviceAsset',
        'basePath' => '@webroot/web_phone/build',
        'baseUrl' => '@web/web_phone/build',
        'js' => [
            'device.min.3.46.1.js',
        ],
        'depends' => [],
        'sourcePath' => null,
        'css' => [],
    ],
    'ActiveFormAsset' => [
        'class' => 'yii\\widgets\\ActiveFormAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'yii-active-form.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ValidationAsset' => [
        'class' => 'yii\\validators\\ValidationAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'yii-validation.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'GridViewAsset' => [
        'class' => 'yii\\grid\\GridViewAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'yii-grid-view.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'PopoverXAsset' => [
        'class' => 'kartik\\popover\\PopoverXAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'popover-x-k.min.js',
        ],
        'css' => [
            'popover-x-k.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikEditableAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikEditableAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'editable-k.min.js',
        ],
        'css' => [
            'editable-k.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikEditablePjaxAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikEditablePjaxAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'editable-pjax-k.min.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikActiveFormAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikActiveFormAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'active-form-k.min.js',
        ],
        'css' => [
            'active-form-k.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'WidgetAsset' => [
        'class' => 'kartik\\base\\WidgetAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-widget-asset.min.js',
        ],
        'css' => [
            'kartik-widget-asset.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'ImperaviAsset' => [
        'class' => 'frontend\\assets\\overridden\\ImperaviAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'imperavi-asset.min.js',
        ],
        'css' => [
            'imperavi-asset.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'MultipleInputAsset' => [
        'class' => 'unclead\\multipleinput\\assets\\MultipleInputAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'multiple-input.min.js',
        ],
        'css' => [
            'multiple-input.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'Select2Asset' => [
        'class' => 'kartik\\select2\\Select2Asset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-select2.min.js',
        ],
        'css' => [
            'kartik-select2.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'Select2KrajeeAsset' => [
        'class' => 'kartik\\select2\\Select2KrajeeAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'krajee-select2.min.js',
        ],
        'css' => [
            'krajee-select2.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'PhoneInputAsset' => [
        'class' => 'borales\\extensions\\phoneInput\\PhoneInputAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'phone-input.min.js',
        ],
        'css' => [
            'phone-input.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'KartikDateRangePickerAsset' => [
        'class' => 'kartik\\daterange\\DateRangePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-date-range-picker.min.js',
        ],
        'css' => [
            'kartik-date-range-picker.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DatePickerAsset' => [
        'class' => 'kartik\\date\\DatePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'bootstrap-datepicker.min.js',
        ],
        'css' => [
            'bootstrap-datepicker.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'CKEditorWidgetAsset' => [
        'class' => 'dosamigos\\ckeditor\\CKEditorWidgetAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'ckeditor-widget.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'Timeline2Asset' => [
        'class' => 'frontend\\assets\\Timeline2Asset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'timeline2.min.js',
        ],
        'css' => [
            'timeline2.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TimelineAsset' => [
        'class' => 'frontend\\assets\\TimelineAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'timeline.min.js',
        ],
        'css' => [
            'timeline.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'DosamigosDatepicker' => [
        'class' => 'dosamigos\\datepicker\\DatePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dosamigos-datepicker.min.js',
        ],
        'css' => [
            'dosamigos-datepicker.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'KartikExportMenuAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikExportMenuAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'export-menu.min.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'ExportColumnAsset' => [
        'class' => 'kartik\\export\\ExportColumnAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'export-column.min.js',
        ],
        'css' => [
            'export-column.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DropdownAsset' => [
        'class' => 'kartik\\bs4dropdown\\DropdownAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dropdown.min.js',
        ],
        'css' => [
            'dropdown.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DialogAsset' => [
        'class' => 'kartik\\dialog\\DialogAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dialog.min.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DialogYiiAsset' => [
        'class' => 'kartik\\dialog\\DialogYiiAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dialog-yii.min.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'BootstrapDialogAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikDialogBootstrapAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dialog-bootstrap.min.js',
        ],
        'css' => [
            'dialog-bootstrap.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'BootstrapProgressbar,' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\BootstrapProgressbar',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'KartikGridViewAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridViewAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'kartik-gridview.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikGridResizeColumnsAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridResizeColumnsAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-grid-resize-column.min.js',
        ],
        'css' => [
            'kartik-grid-resize-column.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikGridExportAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridExportAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-grid-export.min.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikCheckboxColumnAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikCheckboxColumnAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-grid-checkbox.min.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikGridToggleDataAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridToggleDataAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-grid-toggle.min.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikMomentAsset' => [
        'class' => 'kartik\\daterange\\MomentAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-moment.min.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'TimePickerAsset' => [
        'class' => 'kartik\\time\\TimePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-timepicker.min.js',
        ],
        'css' => [
            'kartik-timepicker.min.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'MultiSelectAsset' => [
        'class' => 'dosamigos\\multiselect\\MultiSelectAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dosamigos-multiselect.min.js',
        ],
        'css' => [
            'dosamigos-multiselect.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'LanguagePluginAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\LanguagePluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'language-plugin.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ScanPluginAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\ScanPluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'scan-plugin.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TranslationPluginAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\TranslationPluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'translation-plugin.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'LanguageAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\LanguageAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'language.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'FrontendTranslationAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\FrontendTranslationAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'frontend-translation.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'FrontendTranslationPluginAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\FrontendTranslationPluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'frontend-translation-plugin.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TranslateAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\TranslateAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'translate.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TranslateManagerAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\TranslateManagerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'translate-manager.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TranslatePluginAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\TranslatePluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'translate-plugin.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'LajaxLanguageItemPluginAsset' => [
        'class' => 'frontend\\assets\\overridden\\LajaxLanguageItemPluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'lang-asset.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'DateTimePickerAsset' => [
        'class' => 'dosamigos\\datetimepicker\\DateTimePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dosamigos-datetimepicker.min.js',
        ],
        'css' => [
            'dosamigos-datetimepicker.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'MaskedInputAsset' => [
        'class' => 'yii\\widgets\\MaskedInputAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'maskedinput.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'WebAudioRecorder' => [
        'class' => 'frontend\\assets\\WebAudioRecorder',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'webaudiorecorder.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'WebPhoneAsset' => [
        'class' => 'frontend\\assets\\WebPhoneAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'web-phone.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'CronExpressionAssets' => [
        'class' => 'frontend\\widgets\\cronExpression\\CronExpressionAssets',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'cron-expression.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'HotelAsset' => [
        'class' => 'modules\\hotel\\assets\\HotelAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'hotel-asset.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'UserFlowWidgetAsset' => [
        'class' => 'frontend\\widgets\\frontendWidgetList\\userflow\\assets\\UserFlowWidgetAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'userflow.min.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\web\\JqueryAsset',
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'AllSharedAsset',
        ],
    ],
    'yii\\widgets\\PjaxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'AllSharedAsset',
        ],
    ],
    'frontend\\assets\\groups\\AllSharedAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\widgets\\PjaxAsset',
            'AllSharedAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAllAsset' => [
        'css' => [
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'js' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAllAsset',
    ],
    'frontend\\assets\\groups\\BootstrapGroupAsset' => [
        'sourcePath' => null,
        'basePath' => null,
        'css' => [
            'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css',
        ],
        'js' => [
            'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
        'baseUrl' => null,
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\groups\\BootstrapGroupAsset',
    ],
    'yii\\bootstrap4\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\bootstrap4\\BootstrapPluginAsset',
    ],
    'frontend\\assets\\MomentAsset' => [
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'js' => [
            'https://cdn.jsdelivr.net/npm/moment@2.29/moment.min.js',
        ],
        'depends' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\MomentAsset',
    ],
    'yii\\bootstrap4\\BootstrapAsset' => [
        'sourcePath' => null,
        'css' => [],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
        'js' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\bootstrap4\\BootstrapAsset',
    ],
    'frontend\\assets\\ReactAsset' => [
        'basePath' => null,
        'sourcePath' => null,
        'baseUrl' => '',
        'js' => [
            [
                0 => 'https://unpkg.com/react@16.14.0/umd/react.production.min.js',
                'position' => 1,
                'crossorigin' => true,
            ],
            [
                0 => 'https://unpkg.com/react-dom@16.14.0/umd/react-dom.production.min.js',
                'position' => 1,
                'crossorigin' => true,
            ],
            [
                'https://unpkg.com/babel-standalone@6.26.0/babel.min.js',
            ],
        ],
        'depends' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\ReactAsset',
    ],
    'frontend\\assets\\SimpleBarAsset' => [
        'js' => [
            'https://cdn.jsdelivr.net/npm/simplebar@5.2.1/dist/simplebar.min.js',
        ],
        'css' => [
            'https://cdn.jsdelivr.net/npm/simplebar@5.2.1/dist/simplebar.css',
        ],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\SimpleBarAsset',
    ],
    'dosamigos\\ckeditor\\CKEditorAsset' => [
        'sourcePath' => null,
        'js' => [
            'https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'dosamigos\\ckeditor\\CKEditorAsset',
    ],
    'frontend\\assets\\TwilioAsset' => [
        'js' => [
            'https://sdk.twilio.com/js/client/v1.11/twilio.min.js',
        ],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\TwilioAsset',
    ],
    'lajax\\translatemanager\\bundles\\LanguageItemPluginAsset' => [
        'sourcePath' => null,
        'publishOptions' => [
            'forceCopy' => true,
        ],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'js' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'class' => 'lajax\\translatemanager\\bundles\\LanguageItemPluginAsset',
    ],
    'yii\\jui\\JuiAsset' => [
        'sourcePath' => null,
        'js' => [
            'https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js',
        ],
        'css' => [
            'https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.min.css',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\jui\\JuiAsset',
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'basePath' => null,
        'css' => [
            'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css',
        ],
        'js' => [
            'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
        'baseUrl' => null,
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\groups\\BootstrapGroupAsset',
    ],
    'frontend\\assets\\VueAsset' => [
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'js' => [
            [
                0 => 'https://unpkg.com/vue@3.0/dist/vue.global.js',
                'position' => 2,
            ],
            [
                0 => 'https://cdn.jsdelivr.net/npm/axios@0.21/dist/axios.min.js',
                'position' => 3,
            ],
            [
                0 => 'https://cdn.jsdelivr.net/npm/moment@2.29/moment.min.js',
                'position' => 3,
            ],
            [
                0 => 'https://cdn.jsdelivr.net/npm/moment-timezone@0.5/builds/moment-timezone-with-data.min.js',
                'position' => 3,
            ],
            [
                0 => 'https://cdnjs.cloudflare.com/ajax/libs/libphonenumber-js/1.9.6/libphonenumber-js.min.js',
                'position' => 3,
            ],
        ],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\VueAsset',
    ],
    'frontend\\themes\\gentelella_v2\\assets\\SwitcheryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'AllSharedAsset',
        ],
    ],
    'frontend\\assets\\groups\\AllSharedGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'AllSharedGroupAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAsset' => [
        'sourcePath' => null,
        'basePath' => null,
        'css' => [
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAllAsset',
            'kivork\\bootstrap4glyphicons\\assets\\GlyphiconAsset',
        ],
        'baseUrl' => null,
        'js' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAsset',
    ],
    'kivork\\bootstrap4glyphicons\\assets\\GlyphiconAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'GlyphiconAsset',
        ],
    ],
    'frontend\\assets\\PageLoaderAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'PageLoaderAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'GentelellaGroupAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaCrudGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'GentelellaCrudGroupAsset',
        ],
    ],
    'frontend\\widgets\\notification\\NotificationSocketAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'NotificationSocketAsset',
        ],
    ],
    'frontend\\assets\\CentrifugeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'CentrifugeAsset',
        ],
    ],
    'frontend\\widgets\\clientChat\\ClientChatWidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\AllSharedAsset',
            'frontend\\assets\\MomentAsset',
            'ClientChatWidgetAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\ClientChatAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'ClientChatAsset',
        ],
    ],
    'frontend\\assets\\CallBoxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap4\\BootstrapAsset',
            'CallBoxAsset',
        ],
    ],
    'frontend\\assets\\EditToolAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'EditToolAsset',
        ],
    ],
    'frontend\\widgets\\newWebPhone\\NewWebPhoneAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap4\\BootstrapAsset',
            'frontend\\assets\\ReactAsset',
            'frontend\\assets\\SimpleBarAsset',
            'NewWebPhoneAsset',
        ],
    ],
    'frontend\\widgets\\newWebPhone\\DeviceAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\widgets\\newWebPhone\\NewWebPhoneAsset',
            'DeviceAsset',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'ActiveFormAsset',
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'ValidationAsset',
        ],
    ],
    'yii\\grid\\GridViewAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'GridViewAsset',
        ],
    ],
    'kartik\\popover\\PopoverXAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'PopoverXAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikEditableAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            0 => 'frontend\\assets\\groups\\BootstrapGroupAsset',
            1 => 'frontend\\assets\\groups\\AllSharedAsset',
            3 => 'KartikEditableAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikEditablePjaxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            0 => 'yii\\web\\JqueryAsset',
            1 => 'frontend\\assets\\groups\\BootstrapGroupAsset',
            3 => 'KartikEditablePjaxAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            0 => 'yii\\web\\JqueryAsset',
            1 => 'frontend\\assets\\groups\\BootstrapGroupAsset',
            3 => 'KartikActiveFormAsset',
        ],
    ],
    'kartik\\base\\WidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\groups\\AllSharedAsset',
            'yii\\web\\JqueryAsset',
            'WidgetAsset',
        ],
    ],
    'frontend\\assets\\overridden\\ImperaviAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'ImperaviAsset',
        ],
    ],
    'unclead\\multipleinput\\assets\\MultipleInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'MultipleInputAsset',
        ],
    ],
    'kartik\\select2\\Select2Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'Select2Asset',
        ],
    ],
    'kartik\\select2\\Select2KrajeeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'Select2KrajeeAsset',
        ],
    ],
    'kartik\\select2\\ThemeKrajeeBs4Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'Select2KrajeeAsset',
        ],
    ],
    'kartik\\select2\\ThemeKrajeeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'Select2KrajeeAsset',
        ],
    ],
    'borales\\extensions\\phoneInput\\PhoneInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'PhoneInputAsset',
        ],
    ],
    'kartik\\daterange\\DateRangePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'KartikDateRangePickerAsset',
        ],
    ],
    'kartik\\date\\DatePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'DatePickerAsset',
        ],
    ],
    'dosamigos\\ckeditor\\CKEditorWidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'dosamigos\\ckeditor\\CKEditorAsset',
            'CKEditorWidgetAsset',
        ],
    ],
    'frontend\\assets\\Timeline2Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'Timeline2Asset',
        ],
    ],
    'frontend\\assets\\TimelineAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'TimelineAsset',
        ],
    ],
    'dosamigos\\datepicker\\DatePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'frontend\\assets\\groups\\AllSharedAsset',
            'DosamigosDatepicker',
        ],
    ],
    'frontend\\assets\\overridden\\KartikExportMenuAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'yii\\web\\JqueryAsset',
            2 => 'frontend\\assets\\groups\\BootstrapGroupAsset',
            3 => 'frontend\\assets\\groups\\AllSharedAsset',
            4 => 'kartik\\dialog\\DialogAsset',
            5 => 'KartikExportMenuAsset',
        ],
    ],
    'kartik\\export\\ExportColumnAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'ExportColumnAsset',
        ],
    ],
    'kartik\\bs4dropdown\\DropdownAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap4\\BootstrapAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'DropdownAsset',
        ],
    ],
    'kartik\\dialog\\DialogAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'DialogAsset',
        ],
    ],
    'kartik\\dialog\\DialogYiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'DialogYiiAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikDialogBootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'frontend\\assets\\groups\\AllSharedAsset',
            2 => 'yii\\web\\JqueryAsset',
            3 => 'BootstrapDialogAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\BootstrapProgressbar' => [
        'sourcePath' => null,
        'baseUrl' => null,
        'css' => [
            'https://cdn.jsdelivr.net/npm/bootstrap-progressbar@0.9.0/css/bootstrap-progressbar-3.3.4.min.css',
        ],
        'js' => [
            'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-progressbar/0.9.0/bootstrap-progressbar.min.js',
        ],
        'depends' => [
            'yii\\bootstrap4\\BootstrapPluginAsset',
        ],
        'basePath' => null,
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\BootstrapProgressbar',
    ],
    'frontend\\assets\\overridden\\KartikGridViewAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            2 => 'yii\\web\\YiiAsset',
            3 => 'KartikGridViewAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikGridResizeColumnsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            0 => 'yii\\web\\YiiAsset',
            2 => 'KartikGridResizeColumnsAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikGridExportAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'yii\\web\\YiiAsset',
            2 => 'KartikGridExportAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikCheckboxColumnAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'yii\\web\\YiiAsset',
            2 => 'KartikCheckboxColumnAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikGridToggleDataAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'yii\\web\\YiiAsset',
            2 => 'KartikGridToggleDataAsset',
        ],
    ],
    'kartik\\daterange\\MomentAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'KartikMomentAsset',
        ],
    ],
    'kartik\\time\\TimePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'TimePickerAsset',
        ],
    ],
    'dosamigos\\multiselect\\MultiSelectAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'MultiSelectAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\LanguagePluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'LanguagePluginAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\ScanPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'lajax\\translatemanager\\bundles\\TranslationPluginAsset',
            'ScanPluginAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\TranslationPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'lajax\\translatemanager\\bundles\\LanguageItemPluginAsset',
            'TranslationPluginAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\LanguageAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'LanguageAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\FrontendTranslationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'FrontendTranslationAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\FrontendTranslationPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\jui\\JuiAsset',
            'lajax\\translatemanager\\bundles\\TranslationPluginAsset',
            'FrontendTranslationPluginAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\TranslateAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'TranslateAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\TranslateManagerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'TranslateManagerAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\TranslatePluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'lajax\\translatemanager\\bundles\\TranslationPluginAsset',
            'TranslatePluginAsset',
        ],
    ],
    'frontend\\assets\\overridden\\LajaxLanguageItemPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'LajaxLanguageItemPluginAsset',
        ],
    ],
    'dosamigos\\datetimepicker\\DateTimePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'DateTimePickerAsset',
        ],
    ],
    'yii\\widgets\\MaskedInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'MaskedInputAsset',
        ],
    ],
    'frontend\\assets\\WebAudioRecorder' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'WebAudioRecorder',
        ],
    ],
    'frontend\\assets\\WebPhoneAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap4\\BootstrapAsset',
            'frontend\\assets\\TwilioAsset',
            'WebPhoneAsset',
        ],
    ],
    'frontend\\widgets\\cronExpression\\CronExpressionAssets' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'frontend\\assets\\VueAsset',
            'CronExpressionAssets',
        ],
    ],
    'modules\\hotel\\assets\\HotelAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'HotelAsset',
        ],
    ],
    'frontend\\widgets\\frontendWidgetList\\userflow\\assets\\UserFlowWidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'UserFlowWidgetAsset',
        ],
    ],
];