<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2020-11-25 08:52:49
 */
return [
    'AllSharedAsset' => [
        'class' => 'frontend\\assets\\groups\\AllSharedAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'all-shared-523651321f37ee8d53797700d1a9e10f.js',
        ],
        'css' => [
            'all-shared-49e968a5b4177547ae4fdcbb81d49d53.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'AllSharedGroupAsset' => [
        'class' => 'frontend\\assets\\groups\\AllSharedGroupAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'all-shared-group-1927a4dc16145977bda5806abc928ecd.js',
        ],
        'css' => [
            'all-shared-group-7c2c4f43327efcd4db23ea141f839637.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'GentelellaGroupAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaGroupAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'gentelella-4e7ca6e2d4ec3a56b64b6d085e4f6293.js',
        ],
        'css' => [
            'gentelella-6106d6573a1f598c344e9df82d5bc9bc.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'GentelellaCrudGroupAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaCrudGroupAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'gentelella-crud-group-4e7ca6e2d4ec3a56b64b6d085e4f6293.js',
        ],
        'css' => [
            'gentelella-crud-group-670bde56c03ac96490f685da91724266.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'FontAwesomeAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAsset',
        'basePath' => '@webroot/fontawesome/build',
        'baseUrl' => '@web/fontawesome/build',
        'js' => [],
        'css' => [
            'fontawesome-72c2318c3f1a9ac6f83ee800b7a3bfd9.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'NotificationSocketAsset' => [
        'class' => 'frontend\\widgets\\notification\\NotificationSocketAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'notification-socket-7e23568925985cea6a229be2472713a8.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'CentrifugeAsset' => [
        'class' => 'frontend\\assets\\CentrifugeAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'centrifuge-6baa2c0df222494b235bea0a96c5f092.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ClientChatWidgetAsset' => [
        'class' => 'frontend\\widgets\\clientChat\\ClientChatWidgetAsset',
        'basePath' => '@webroot/client_chat/build',
        'baseUrl' => '@web/client_chat/build',
        'js' => [
            'client_chat_widget-604d2b26f92478554a549980154fd029.js',
        ],
        'css' => [
            'client_chat_widget-6b2f2ff5d4b32fa8a689760f85e81843.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ClientChatAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\ClientChatAsset',
        'basePath' => '@webroot/client_chat/build',
        'baseUrl' => '@web/client_chat/build',
        'js' => [
            'client_chat-dfcaf98720cc0b605d12ff3c8e1d30f5.js',
        ],
        'css' => [
            'client_chat-63531f0af0859ef4bc8533e16326c9ae.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'CallBoxAsset' => [
        'class' => 'frontend\\assets\\CallBoxAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/client_chat/build',
        'js' => [
            'call_box-99f33f4511a00991cfc858ca0346c837.js',
        ],
        'css' => [
            'call_box-158640470132a64b3115ffc47b10654b.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'EditToolAsset' => [
        'class' => 'frontend\\assets\\EditToolAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/client_chat/build',
        'js' => [
            'edit_tool-6a8967dac8b53c8ce3834f82ccdf85da.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'NewWebPhoneGroupAsset' => [
        'class' => 'frontend\\widgets\\newWebPhone\\NewWebPhoneGroupAsset',
        'basePath' => '@webroot/web_phone/build',
        'baseUrl' => '@web/web_phone/build',
        'js' => [
            'web_phone-351c2a6b36be82ade7ddb261ec40b30b.js',
        ],
        'css' => [
            'web_phone-3dcf9e219b0a6a0878decf89c2cab8ef.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ActiveFormAsset' => [
        'class' => 'yii\\widgets\\ActiveFormAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'yii-active-form-3b9367a8139c757f590de64c359de2ea.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ValidationAsset' => [
        'class' => 'yii\\validators\\ValidationAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'yii-validation-8309d401e581c6135e6d70a418a90e01.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'GridViewAsset' => [
        'class' => 'yii\\grid\\GridViewAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'yii-grid-view-323af3dceea36bd5a22e8894119d1432.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'PopoverXAsset' => [
        'class' => 'kartik\\popover\\PopoverXAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'popover-x-k-c3c6afd9f55c12e296fc6457f2923893.js',
        ],
        'css' => [
            'popover-x-k-d5242f6ba399ca3e57c91aaaf65d06e9.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikEditableAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikEditableAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'editable-k-5a2fa5d8fa4315b10a9184c255104295.js',
        ],
        'css' => [
            'editable-k-25a8cc733ecaa9e0d30cbb97d89a1b6c.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikEditablePjaxAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikEditablePjaxAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'editable-pjax-k-ca8fff6fe0e50d9595a549e79d48e18e.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikActiveFormAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikActiveFormAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'active-form-k-7b2dfe23344eefcb57ea4860fa500e83.js',
        ],
        'css' => [
            'active-form-284eccd30c76d5898e6f21977a1a0603.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'WidgetAsset' => [
        'class' => 'kartik\\base\\WidgetAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-widget-asset-5f95ba5ba72460d4e0f5d1e37c072ba0.js',
        ],
        'css' => [
            'kartik-widget-asset-3aa9ce6d1a481385d797c33016f4a979.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'ImperaviAsset' => [
        'class' => 'frontend\\assets\\overridden\\ImperaviAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'imperavi-asset-2a3bf0cd8b063aeb7b8cc52d0037c556.js',
        ],
        'css' => [
            'imperavi-asset-25bcf96b10bf4bbe9a8e8c6ccf62536a.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'MultipleInputAsset' => [
        'class' => 'unclead\\multipleinput\\assets\\MultipleInputAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'multiple-input-0a3ab30113f5597ef5c34164ca6de332.js',
        ],
        'css' => [
            'multiple-input-e52c3523f34ad3ebe975545e937e5013.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'Select2Asset' => [
        'class' => 'kartik\\select2\\Select2Asset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-select2-25d0daba509a72dd557d1d66ad93ea4f.js',
        ],
        'css' => [
            'kartik-select2-9e3f8a2cc4d3ca2cad37f1bac3eb9170.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'Select2KrajeeAsset' => [
        'class' => 'kartik\\select2\\Select2KrajeeAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'krajee-select2-a52de20770554561bbd482d75eb68dc5.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'PhoneInputAsset' => [
        'class' => 'borales\\extensions\\phoneInput\\PhoneInputAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'phone-input-df52245006a5096d43bf089fee1eb2df.js',
        ],
        'css' => [
            'phone-input-41000d6226c4914e45d9d3fec766ffea.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'KartikDateRangePickerAsset' => [
        'class' => 'kartik\\daterange\\DateRangePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-date-range-picker-1779959d066a3c878566b50c29e094c1.js',
        ],
        'css' => [
            'kartik-date-range-picker-009ca4b52b727302acd5e3acca081518.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DatePickerAsset' => [
        'class' => 'kartik\\date\\DatePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'bootstrap-datepicker-6e3008c3b758bb640a5e716912629f49.js',
        ],
        'css' => [
            'bootstrap-datepicker-e81b54a24fa5a57cc0da499b1f444d8f.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'CKEditorWidgetAsset' => [
        'class' => 'dosamigos\\ckeditor\\CKEditorWidgetAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'ckeditor-widget-b410644e0e98d8f143be52e216aa0a37.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'Timeline2Asset' => [
        'class' => 'frontend\\assets\\Timeline2Asset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'timeline2-20700129e9b376314774ad0ddd472f10.js',
        ],
        'css' => [
            'timeline2-fadd397385570e2093f468d0dc9d462f.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TimelineAsset' => [
        'class' => 'frontend\\assets\\TimelineAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'timeline-61d58f8e987d83f33442517de01aa5c5.js',
        ],
        'css' => [
            'timeline-732f6ea36efcfedbdfcec092b2595af0.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'DosamigosDatepicker' => [
        'class' => 'dosamigos\\datepicker\\DatePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dosamigos-datepicker-10465bab3abda3b219ea000b29d03848.js',
        ],
        'css' => [
            'dosamigos-datepicker-2c949d22d099d84b172edf2800715a8d.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'KDNJsonEditorAsset' => [
        'class' => 'frontend\\assets\\overridden\\KDNJsonEditorAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'jsoneditor-e786633f67f96e77248520db8d629a8f.js',
        ],
        'css' => [
            'jsoneditor-a3bd982c93a3e8f9831d34768acdab05.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'KartikExportMenuAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikExportMenuAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'export-menu-89d44d3aa5a2fb8824a070e41744f6c4.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'ExportColumnAsset' => [
        'class' => 'kartik\\export\\ExportColumnAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'export-column-80db89e0c9b903860247ffe9c9241332.js',
        ],
        'css' => [
            'export-column-e9bd01f520de7ca64c89982aea06de48.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DropdownAsset' => [
        'class' => 'kartik\\bs4dropdown\\DropdownAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dropdown-be044bb2905a4117714d2d5b13848c74.js',
        ],
        'css' => [
            'dropdown-c89c9f7288aeaca474e07ee016d97a87.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DialogAsset' => [
        'class' => 'kartik\\dialog\\DialogAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dialog-af5e3d1950025544409353062887457d.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DialogYiiAsset' => [
        'class' => 'kartik\\dialog\\DialogYiiAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dialog-yii-52642f44a55a68159d0c7d463410acfd.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'BootstrapDialogAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikDialogBootstrapAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dialog-bootstrap-a3593da9a8b044edd31cb6987fd29014.js',
        ],
        'css' => [
            'dialog-bootstrap-c2feb7436a8aad89eb9e5c0c82730249.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikGridViewAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridViewAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'kartik-gridview-930eb85fb7809154c6050441fc2fe616.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikGridResizeColumnsAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridResizeColumnsAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-grid-resize-column-9a23d58d99f75de6e7be1be38505fb2f.js',
        ],
        'css' => [
            'kartik-grid-resize-column-4fb1a554fa603e49b44b123af00a2071.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikGridExportAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridExportAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-grid-export-73f97f33c612b4023ccef5a6269be772.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'MaskedInputAsset' => [
        'class' => 'yii\\widgets\\MaskedInputAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'maskedinput-6fbaaa2a1d50996e1b1454a68f3b7f29.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'AllSharedAsset',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'AllSharedAsset',
        ],
    ],
    'yii\\widgets\\PjaxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'AllSharedAsset',
        ],
    ],
    'yii\\bootstrap4\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'AllSharedAsset',
        ],
    ],
    'yii\\bootstrap4\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap4\\BootstrapAsset',
            'AllSharedAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\BootstrapProgressbar' => [
        'sourcePath' => null,
        'baseUrl' => null,
        'css' => [
            'https://cdn.jsdelivr.net/npm/bootstrap-progressbar@0.9.0/css/bootstrap-progressbar-3.3.4.min.css',
        ],
        'js' => [
            'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-progressbar/0.9.0/bootstrap-progressbar.min.js',
        ],
        'depends' => [
            'yii\\bootstrap4\\BootstrapPluginAsset',
        ],
        'basePath' => null,
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\BootstrapProgressbar',
    ],
    'frontend\\assets\\groups\\AllSharedAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\web\\YiiAsset',
            'yii\\widgets\\PjaxAsset',
            'frontend\\themes\\gentelella_v2\\assets\\BootstrapProgressbar',
            'AllSharedAsset',
        ],
    ],
    'frontend\\assets\\MomentAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'AllSharedAsset',
        ],
    ],
    'kartik\\select2\\Select2KrajeeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'AllSharedAsset',
        ],
    ],
    'dosamigos\\ckeditor\\CKEditorAsset' => [
        'sourcePath' => null,
        'js' => [
            'https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js',
        ],
        'depends' => [],
        'basePath' => null,
        'baseUrl' => null,
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'dosamigos\\ckeditor\\CKEditorAsset',
    ],
    'frontend\\assets\\groups\\AllSharedGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'AllSharedGroupAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'GentelellaGroupAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaCrudGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'GentelellaCrudGroupAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'FontAwesomeAsset',
        ],
    ],
    'kivork\\bootstrap4glyphicons\\assets\\GlyphiconAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'FontAwesomeAsset',
        ],
    ],
    'frontend\\widgets\\notification\\NotificationSocketAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'NotificationSocketAsset',
        ],
    ],
    'frontend\\assets\\CentrifugeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'CentrifugeAsset',
        ],
    ],
    'frontend\\widgets\\clientChat\\ClientChatWidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\groups\\AllSharedAsset',
            'frontend\\assets\\MomentAsset',
            'ClientChatWidgetAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\ClientChatAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'ClientChatAsset',
        ],
    ],
    'frontend\\assets\\CallBoxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'CallBoxAsset',
        ],
    ],
    'frontend\\assets\\EditToolAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'EditToolAsset',
        ],
    ],
    'frontend\\widgets\\newWebPhone\\NewWebPhoneGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'NewWebPhoneGroupAsset',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'ActiveFormAsset',
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'ValidationAsset',
        ],
    ],
    'yii\\grid\\GridViewAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'GridViewAsset',
        ],
    ],
    'kartik\\popover\\PopoverXAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'PopoverXAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikEditableAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            0 => 'frontend\\assets\\groups\\AllSharedAsset',
            2 => 'KartikEditableAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikEditablePjaxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'KartikEditablePjaxAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'KartikActiveFormAsset',
        ],
    ],
    'kartik\\base\\WidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\groups\\AllSharedAsset',
            'WidgetAsset',
        ],
    ],
    'frontend\\assets\\overridden\\ImperaviAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'ImperaviAsset',
        ],
    ],
    'unclead\\multipleinput\\assets\\MultipleInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'MultipleInputAsset',
        ],
    ],
    'kartik\\select2\\Select2Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'Select2Asset',
        ],
    ],
    'kartik\\select2\\ThemeKrajeeBs4Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'Select2KrajeeAsset',
        ],
    ],
    'kartik\\select2\\ThemeKrajeeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'Select2KrajeeAsset',
        ],
    ],
    'borales\\extensions\\phoneInput\\PhoneInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'PhoneInputAsset',
        ],
    ],
    'kartik\\daterange\\DateRangePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\MomentAsset',
            'KartikDateRangePickerAsset',
        ],
    ],
    'kartik\\date\\DatePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'DatePickerAsset',
        ],
    ],
    'dosamigos\\ckeditor\\CKEditorWidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'dosamigos\\ckeditor\\CKEditorAsset',
            'CKEditorWidgetAsset',
        ],
    ],
    'frontend\\assets\\Timeline2Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'Timeline2Asset',
        ],
    ],
    'frontend\\assets\\TimelineAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'TimelineAsset',
        ],
    ],
    'dosamigos\\datepicker\\DatePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'DosamigosDatepicker',
        ],
    ],
    'frontend\\assets\\overridden\\KDNJsonEditorAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'KDNJsonEditorAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikExportMenuAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'frontend\\assets\\groups\\AllSharedAsset',
            2 => 'kartik\\dialog\\DialogAsset',
            3 => 'KartikExportMenuAsset',
        ],
    ],
    'kartik\\export\\ExportColumnAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'ExportColumnAsset',
        ],
    ],
    'kartik\\bs4dropdown\\DropdownAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap4\\BootstrapAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'DropdownAsset',
        ],
    ],
    'kartik\\dialog\\DialogAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'DialogAsset',
        ],
    ],
    'kartik\\dialog\\DialogYiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'DialogYiiAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikDialogBootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'frontend\\assets\\groups\\AllSharedAsset',
            2 => 'BootstrapDialogAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikGridViewAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            2 => 'yii\\web\\YiiAsset',
            3 => 'KartikGridViewAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikGridResizeColumnsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            0 => 'yii\\web\\YiiAsset',
            2 => 'KartikGridResizeColumnsAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikGridExportAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'yii\\web\\YiiAsset',
            2 => 'KartikGridExportAsset',
        ],
    ],
    'yii\\widgets\\MaskedInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'MaskedInputAsset',
        ],
    ],
];