<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2020-12-24 11:28:28
 */
return [
    'FontAwesomeAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAsset',
        'basePath' => '@webroot/fontawesome/build',
        'baseUrl' => '@web/fontawesome/build',
        'js' => '',
        'css' => '',
        'depends' => [],
        'sourcePath' => null,
    ],
    'GlyphiconAsset' => [
        'class' => 'kivork\\bootstrap4glyphicons\\assets\\GlyphiconAsset',
        'basePath' => '@webroot/fontawesome/build',
        'baseUrl' => '@web/fontawesome/build',
        'js' => [],
        'css' => [
            'glyphicon-b6155b8d4a239ea789c349d4dc1580b5.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'PageLoaderAsset' => [
        'class' => 'frontend\\assets\\PageLoaderAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'page-loader-a7485f9508cf185726a0136d8f2c3436.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'AllSharedAsset' => [
        'class' => 'frontend\\assets\\groups\\AllSharedAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'all-shared-7daff6ee92a5aeac007a30cabc6740dd.js',
        ],
        'css' => [
            'all-shared-eb81dc77070dbed66637c0696f1906ad.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'AllSharedGroupAsset' => [
        'class' => 'frontend\\assets\\groups\\AllSharedGroupAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'all-shared-group-f893a6e4d4ae5d63c9ba769df1191971.js',
        ],
        'css' => [
            'all-shared-group-7c2c4f43327efcd4db23ea141f839637.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'GentelellaGroupAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaGroupAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'gentelella-4e7ca6e2d4ec3a56b64b6d085e4f6293.js',
        ],
        'css' => [
            'gentelella-6106d6573a1f598c344e9df82d5bc9bc.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'GentelellaCrudGroupAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaCrudGroupAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'gentelella-crud-group-4e7ca6e2d4ec3a56b64b6d085e4f6293.js',
        ],
        'css' => [
            'gentelella-crud-group-670bde56c03ac96490f685da91724266.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'NotificationSocketAsset' => [
        'class' => 'frontend\\widgets\\notification\\NotificationSocketAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'notification-socket-7e23568925985cea6a229be2472713a8.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'CentrifugeAsset' => [
        'class' => 'frontend\\assets\\CentrifugeAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'centrifuge-6baa2c0df222494b235bea0a96c5f092.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ClientChatWidgetAsset' => [
        'class' => 'frontend\\widgets\\clientChat\\ClientChatWidgetAsset',
        'basePath' => '@webroot/client_chat/build',
        'baseUrl' => '@web/client_chat/build',
        'js' => [
            'client_chat_widget-cf48ffeda55e3c6343d2c40d34127f5c.js',
        ],
        'css' => [
            'client_chat_widget-6b2f2ff5d4b32fa8a689760f85e81843.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ClientChatAsset' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\ClientChatAsset',
        'basePath' => '@webroot/client_chat/build',
        'baseUrl' => '@web/client_chat/build',
        'js' => [
            'client_chat-67154d56d2f9ba2bf6e817654a1ebce6.js',
        ],
        'css' => [
            'client_chat-e1c27b57ef4d3e5d5d7a79729135af75.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'CallBoxAsset' => [
        'class' => 'frontend\\assets\\CallBoxAsset',
        'basePath' => '@webroot/client_chat/build',
        'baseUrl' => '@web/client_chat/build',
        'js' => [
            'call_box-99f33f4511a00991cfc858ca0346c837.js',
        ],
        'css' => [
            'call_box-158640470132a64b3115ffc47b10654b.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'EditToolAsset' => [
        'class' => 'frontend\\assets\\EditToolAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'edit_tool-6a8967dac8b53c8ce3834f82ccdf85da.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'NewWebPhoneGroupAsset' => [
        'class' => 'frontend\\widgets\\newWebPhone\\NewWebPhoneGroupAsset',
        'basePath' => '@webroot/web_phone/build',
        'baseUrl' => '@web/web_phone/build',
        'js' => [
            'web_phone-b0068a8ecbaba7e1b07862e09d24361b.js',
        ],
        'css' => [
            'web_phone-3dcf9e219b0a6a0878decf89c2cab8ef.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ActiveFormAsset' => [
        'class' => 'yii\\widgets\\ActiveFormAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'yii-active-form-3b9367a8139c757f590de64c359de2ea.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ValidationAsset' => [
        'class' => 'yii\\validators\\ValidationAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'yii-validation-8309d401e581c6135e6d70a418a90e01.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'GridViewAsset' => [
        'class' => 'yii\\grid\\GridViewAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'yii-grid-view-323af3dceea36bd5a22e8894119d1432.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'PopoverXAsset' => [
        'class' => 'kartik\\popover\\PopoverXAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'popover-x-k-c3c6afd9f55c12e296fc6457f2923893.js',
        ],
        'css' => [
            'popover-x-k-a0116594568b852120955a5408e3683a.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikEditableAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikEditableAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'editable-k-0d2b7954330e8cfd4d356a9d88442ce1.js',
        ],
        'css' => [
            'editable-k-5f02a5079b58bd732e5b9d594eb61a32.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikEditablePjaxAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikEditablePjaxAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'editable-pjax-k-ca8fff6fe0e50d9595a549e79d48e18e.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikActiveFormAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikActiveFormAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'active-form-k-7b2dfe23344eefcb57ea4860fa500e83.js',
        ],
        'css' => [
            'active-form-284eccd30c76d5898e6f21977a1a0603.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'WidgetAsset' => [
        'class' => 'kartik\\base\\WidgetAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-widget-asset-5f95ba5ba72460d4e0f5d1e37c072ba0.js',
        ],
        'css' => [
            'kartik-widget-asset-a470d832351b6ca7360eb6d304a56dc7.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'ImperaviAsset' => [
        'class' => 'frontend\\assets\\overridden\\ImperaviAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'imperavi-asset-ab63783c7969e8e5b90df65d7533016c.js',
        ],
        'css' => [
            'imperavi-asset-25bcf96b10bf4bbe9a8e8c6ccf62536a.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'MultipleInputAsset' => [
        'class' => 'unclead\\multipleinput\\assets\\MultipleInputAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'multiple-input-0a3ab30113f5597ef5c34164ca6de332.js',
        ],
        'css' => [
            'multiple-input-e52c3523f34ad3ebe975545e937e5013.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'Select2Asset' => [
        'class' => 'kartik\\select2\\Select2Asset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-select2-25d0daba509a72dd557d1d66ad93ea4f.js',
        ],
        'css' => [
            'kartik-select2-9e3f8a2cc4d3ca2cad37f1bac3eb9170.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'Select2KrajeeAsset' => [
        'class' => 'kartik\\select2\\Select2KrajeeAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'krajee-select2-39f34a83a75286ca175cd8386ada1b95.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'PhoneInputAsset' => [
        'class' => 'borales\\extensions\\phoneInput\\PhoneInputAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'phone-input-5b702678f4fb75d4515604b375276031.js',
        ],
        'css' => [
            'phone-input-55321758f5ad10b006abbdbc7f82f383.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'KartikDateRangePickerAsset' => [
        'class' => 'kartik\\daterange\\DateRangePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-date-range-picker-1779959d066a3c878566b50c29e094c1.js',
        ],
        'css' => [
            'kartik-date-range-picker-009ca4b52b727302acd5e3acca081518.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DatePickerAsset' => [
        'class' => 'kartik\\date\\DatePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'bootstrap-datepicker-6e3008c3b758bb640a5e716912629f49.js',
        ],
        'css' => [
            'bootstrap-datepicker-e81b54a24fa5a57cc0da499b1f444d8f.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'CKEditorWidgetAsset' => [
        'class' => 'dosamigos\\ckeditor\\CKEditorWidgetAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'ckeditor-widget-b410644e0e98d8f143be52e216aa0a37.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'Timeline2Asset' => [
        'class' => 'frontend\\assets\\Timeline2Asset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'timeline2-13174c3726fb18d308f49d0095621711.js',
        ],
        'css' => [
            'timeline2-fadd397385570e2093f468d0dc9d462f.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TimelineAsset' => [
        'class' => 'frontend\\assets\\TimelineAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'timeline-61d58f8e987d83f33442517de01aa5c5.js',
        ],
        'css' => [
            'timeline-732f6ea36efcfedbdfcec092b2595af0.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'DosamigosDatepicker' => [
        'class' => 'dosamigos\\datepicker\\DatePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dosamigos-datepicker-10465bab3abda3b219ea000b29d03848.js',
        ],
        'css' => [
            'dosamigos-datepicker-2c949d22d099d84b172edf2800715a8d.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'KDNJsonEditorAsset' => [
        'class' => 'frontend\\assets\\overridden\\KDNJsonEditorAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'jsoneditor-c75097cab8b9243ae6035b64c4a49ad0.js',
        ],
        'css' => [
            'jsoneditor-f375c3c546749e6112f89635d21a332f.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'KartikExportMenuAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikExportMenuAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'export-menu-89d44d3aa5a2fb8824a070e41744f6c4.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'ExportColumnAsset' => [
        'class' => 'kartik\\export\\ExportColumnAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'export-column-80db89e0c9b903860247ffe9c9241332.js',
        ],
        'css' => [
            'export-column-e9bd01f520de7ca64c89982aea06de48.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DropdownAsset' => [
        'class' => 'kartik\\bs4dropdown\\DropdownAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dropdown-be044bb2905a4117714d2d5b13848c74.js',
        ],
        'css' => [
            'dropdown-c89c9f7288aeaca474e07ee016d97a87.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DialogAsset' => [
        'class' => 'kartik\\dialog\\DialogAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dialog-af5e3d1950025544409353062887457d.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'DialogYiiAsset' => [
        'class' => 'kartik\\dialog\\DialogYiiAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dialog-yii-52642f44a55a68159d0c7d463410acfd.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'BootstrapDialogAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikDialogBootstrapAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dialog-bootstrap-a3593da9a8b044edd31cb6987fd29014.js',
        ],
        'css' => [
            'dialog-bootstrap-c2feb7436a8aad89eb9e5c0c82730249.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'BootstrapProgressbar,' => [
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\BootstrapProgressbar',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'KartikGridViewAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridViewAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'kartik-gridview-470a9568bc3c3012fad83608f8a77dc1.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikGridResizeColumnsAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridResizeColumnsAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-grid-resize-column-9a23d58d99f75de6e7be1be38505fb2f.js',
        ],
        'css' => [
            'kartik-grid-resize-column-4fb1a554fa603e49b44b123af00a2071.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikGridExportAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridExportAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-grid-export-73f97f33c612b4023ccef5a6269be772.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikCheckboxColumnAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikCheckboxColumnAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-grid-checkbox-faaaddf7453c96f00cb0d5f713b59b9e.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikGridToggleDataAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridToggleDataAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-grid-toggle-e6092ca9af57ce82ef8909d79e5cdba2.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikMomentAsset' => [
        'class' => 'kartik\\daterange\\MomentAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-moment-cc146c009cab950f0668cde13818bbb3.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'KartikGridFloatHeadAsset' => [
        'class' => 'frontend\\assets\\overridden\\KartikGridFloatHeadAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-gridfloathead-a222b3b8945ffd8c385e33f9424418b1.js',
        ],
        'css' => [],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'TimePickerAsset' => [
        'class' => 'kartik\\time\\TimePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'kartik-timepicker-4c971dd920b5825c41b8dc59804d59e2.js',
        ],
        'css' => [
            'kartik-timepicker-ec95f18a96c7e1fab453a5e785f02199.css',
        ],
        'depends' => [],
        'bsPluginEnabled' => false,
        'bsDependencyEnabled' => false,
        'sourcePath' => null,
    ],
    'MultiSelectAsset' => [
        'class' => 'dosamigos\\multiselect\\MultiSelectAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dosamigos-multiselect-0c913aac00b62a7ec3926b2bf249e3f8.js',
        ],
        'css' => [
            'dosamigos-multiselect-c16c7aae2002c4375733fed4f1a83356.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'LanguagePluginAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\LanguagePluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'language-plugin-9ee091c382d3488772d0631b361830db.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'ScanPluginAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\ScanPluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'scan-plugin-fd283696cffdad6718dd3a83ee45d2cc.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TranslationPluginAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\TranslationPluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'translation-plugin-c3b61d997668dc5cbd7b3ea657d1f122.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'LanguageAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\LanguageAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'language-7b87e9b0a903a5ea040754398c884603.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'FrontendTranslationAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\FrontendTranslationAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'frontend-translation-a36a813d257d4e3bfeae020aafabad6d.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'FrontendTranslationPluginAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\FrontendTranslationPluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'frontend-translation-plugin-fd4bca5bcea42255da0b0776a7081ba0.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TranslateAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\TranslateAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'translate-587814b86808ee0b6d364cac944c168d.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TranslateManagerAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\TranslateManagerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'translate-manager-e023631d156b86a04e13cf3e1f8c52b5.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'TranslatePluginAsset' => [
        'class' => 'lajax\\translatemanager\\bundles\\TranslatePluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'translate-plugin-f7a17ad02a54a87395859b4f9b7f73bb.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'LajaxLanguageItemPluginAsset' => [
        'class' => 'frontend\\assets\\overridden\\LajaxLanguageItemPluginAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'lang-asset-335ce29fa18b80f973b797f760f1b41c.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'DateTimePickerAsset' => [
        'class' => 'dosamigos\\datetimepicker\\DateTimePickerAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'dosamigos-datetimepicker-e99d8ca496bb1ba2b5399e780c7d579e.js',
        ],
        'css' => [
            'dosamigos-datetimepicker-a8baffaa077a3bf11c8c9aee47193974.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'MaskedInputAsset' => [
        'class' => 'yii\\widgets\\MaskedInputAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'maskedinput-6fbaaa2a1d50996e1b1454a68f3b7f29.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'WebAudioRecorder' => [
        'class' => 'frontend\\assets\\WebAudioRecorder',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [
            'webaudiorecorder-731b062db4170902f7f4f8163a5dfb27.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'WebPhoneAsset' => [
        'class' => 'frontend\\assets\\WebPhoneAsset',
        'basePath' => '@webroot/all_shared/build',
        'baseUrl' => '@web/all_shared/build',
        'js' => [],
        'css' => [
            'web-phone-e1db23b6b6baefc5d88c7f31a35241cf.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAsset' => [
        'sourcePath' => null,
        'basePath' => null,
        'css' => [
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAllAsset',
            'kivork\\bootstrap4glyphicons\\assets\\GlyphiconAsset',
        ],
        'baseUrl' => null,
        'js' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAsset',
    ],
    'kivork\\bootstrap4glyphicons\\assets\\GlyphiconAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'GlyphiconAsset',
        ],
    ],
    'frontend\\assets\\PageLoaderAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'PageLoaderAsset',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\web\\JqueryAsset',
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'AllSharedAsset',
        ],
    ],
    'yii\\widgets\\PjaxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'AllSharedAsset',
        ],
    ],
    'frontend\\assets\\groups\\AllSharedAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\widgets\\PjaxAsset',
            'AllSharedAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAllAsset' => [
        'css' => [
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'js' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\FontAwesomeAllAsset',
    ],
    'frontend\\assets\\groups\\BootstrapGroupAsset' => [
        'sourcePath' => null,
        'basePath' => null,
        'css' => [
            'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css',
        ],
        'js' => [
            'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
        'baseUrl' => null,
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\groups\\BootstrapGroupAsset',
    ],
    'yii\\bootstrap4\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\bootstrap4\\BootstrapPluginAsset',
    ],
    'frontend\\assets\\MomentAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'AllSharedAsset',
        ],
    ],
    'yii\\bootstrap4\\BootstrapAsset' => [
        'sourcePath' => null,
        'css' => [],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
        'js' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\bootstrap4\\BootstrapAsset',
    ],
    'kartik\\select2\\Select2KrajeeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'AllSharedAsset',
        ],
    ],
    'dosamigos\\ckeditor\\CKEditorAsset' => [
        'sourcePath' => null,
        'js' => [
            'https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'dosamigos\\ckeditor\\CKEditorAsset',
    ],
    'frontend\\assets\\TwilioAsset' => [
        'js' => [
            'https://sdk.twilio.com/js/client/v1.10/twilio.min.js',
        ],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\TwilioAsset',
    ],
    'lajax\\translatemanager\\bundles\\LanguageItemPluginAsset' => [
        'sourcePath' => null,
        'publishOptions' => [
            'forceCopy' => true,
        ],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'js' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'class' => 'lajax\\translatemanager\\bundles\\LanguageItemPluginAsset',
    ],
    'yii\\jui\\JuiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'AllSharedAsset',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'basePath' => null,
        'css' => [
            'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css',
        ],
        'js' => [
            'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
        'baseUrl' => null,
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\assets\\groups\\BootstrapGroupAsset',
    ],
    'frontend\\assets\\groups\\AllSharedGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'AllSharedGroupAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'GentelellaGroupAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\groups\\GentelellaCrudGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'GentelellaCrudGroupAsset',
        ],
    ],
    'frontend\\widgets\\notification\\NotificationSocketAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'NotificationSocketAsset',
        ],
    ],
    'frontend\\assets\\CentrifugeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'CentrifugeAsset',
        ],
    ],
    'frontend\\widgets\\clientChat\\ClientChatWidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\AllSharedAsset',
            'frontend\\assets\\MomentAsset',
            'ClientChatWidgetAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\ClientChatAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'ClientChatAsset',
        ],
    ],
    'frontend\\assets\\CallBoxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap4\\BootstrapAsset',
            'CallBoxAsset',
        ],
    ],
    'frontend\\assets\\EditToolAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'EditToolAsset',
        ],
    ],
    'frontend\\widgets\\newWebPhone\\NewWebPhoneGroupAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'NewWebPhoneGroupAsset',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'ActiveFormAsset',
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'ValidationAsset',
        ],
    ],
    'yii\\grid\\GridViewAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'GridViewAsset',
        ],
    ],
    'kartik\\popover\\PopoverXAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'PopoverXAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikEditableAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            0 => 'frontend\\assets\\groups\\BootstrapGroupAsset',
            1 => 'frontend\\assets\\groups\\AllSharedAsset',
            3 => 'KartikEditableAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikEditablePjaxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            0 => 'yii\\web\\JqueryAsset',
            1 => 'frontend\\assets\\groups\\BootstrapGroupAsset',
            3 => 'KartikEditablePjaxAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            0 => 'yii\\web\\JqueryAsset',
            1 => 'frontend\\assets\\groups\\BootstrapGroupAsset',
            3 => 'KartikActiveFormAsset',
        ],
    ],
    'kartik\\base\\WidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\groups\\AllSharedAsset',
            'yii\\web\\JqueryAsset',
            'WidgetAsset',
        ],
    ],
    'frontend\\assets\\overridden\\ImperaviAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'ImperaviAsset',
        ],
    ],
    'unclead\\multipleinput\\assets\\MultipleInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'MultipleInputAsset',
        ],
    ],
    'kartik\\select2\\Select2Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'Select2Asset',
        ],
    ],
    'kartik\\select2\\ThemeKrajeeBs4Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'Select2KrajeeAsset',
        ],
    ],
    'kartik\\select2\\ThemeKrajeeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'Select2KrajeeAsset',
        ],
    ],
    'borales\\extensions\\phoneInput\\PhoneInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'PhoneInputAsset',
        ],
    ],
    'kartik\\daterange\\DateRangePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'KartikDateRangePickerAsset',
        ],
    ],
    'kartik\\date\\DatePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'DatePickerAsset',
        ],
    ],
    'dosamigos\\ckeditor\\CKEditorWidgetAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'dosamigos\\ckeditor\\CKEditorAsset',
            'CKEditorWidgetAsset',
        ],
    ],
    'frontend\\assets\\Timeline2Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'Timeline2Asset',
        ],
    ],
    'frontend\\assets\\TimelineAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'TimelineAsset',
        ],
    ],
    'dosamigos\\datepicker\\DatePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'frontend\\assets\\groups\\AllSharedAsset',
            'DosamigosDatepicker',
        ],
    ],
    'frontend\\assets\\overridden\\KDNJsonEditorAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'KDNJsonEditorAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikExportMenuAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'yii\\web\\JqueryAsset',
            2 => 'frontend\\assets\\groups\\BootstrapGroupAsset',
            3 => 'frontend\\assets\\groups\\AllSharedAsset',
            4 => 'kartik\\dialog\\DialogAsset',
            5 => 'KartikExportMenuAsset',
        ],
    ],
    'kartik\\export\\ExportColumnAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'ExportColumnAsset',
        ],
    ],
    'kartik\\bs4dropdown\\DropdownAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap4\\BootstrapAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'DropdownAsset',
        ],
    ],
    'kartik\\dialog\\DialogAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'DialogAsset',
        ],
    ],
    'kartik\\dialog\\DialogYiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'DialogYiiAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikDialogBootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'frontend\\assets\\groups\\AllSharedAsset',
            2 => 'yii\\web\\JqueryAsset',
            3 => 'BootstrapDialogAsset',
        ],
    ],
    'frontend\\themes\\gentelella_v2\\assets\\BootstrapProgressbar' => [
        'sourcePath' => null,
        'baseUrl' => null,
        'css' => [
            'https://cdn.jsdelivr.net/npm/bootstrap-progressbar@0.9.0/css/bootstrap-progressbar-3.3.4.min.css',
        ],
        'js' => [
            'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-progressbar/0.9.0/bootstrap-progressbar.min.js',
        ],
        'depends' => [
            'yii\\bootstrap4\\BootstrapPluginAsset',
        ],
        'basePath' => null,
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'frontend\\themes\\gentelella_v2\\assets\\BootstrapProgressbar',
    ],
    'frontend\\assets\\overridden\\KartikGridViewAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            2 => 'yii\\web\\YiiAsset',
            3 => 'KartikGridViewAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikGridResizeColumnsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            0 => 'yii\\web\\YiiAsset',
            2 => 'KartikGridResizeColumnsAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikGridExportAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'yii\\web\\YiiAsset',
            2 => 'KartikGridExportAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikCheckboxColumnAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'yii\\web\\YiiAsset',
            2 => 'KartikCheckboxColumnAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikGridToggleDataAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'yii\\web\\YiiAsset',
            2 => 'KartikGridToggleDataAsset',
        ],
    ],
    'kartik\\daterange\\MomentAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'KartikMomentAsset',
        ],
    ],
    'frontend\\assets\\overridden\\KartikGridFloatHeadAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            1 => 'yii\\web\\JqueryAsset',
            2 => 'frontend\\assets\\groups\\BootstrapGroupAsset',
            3 => 'KartikGridFloatHeadAsset',
        ],
    ],
    'kartik\\time\\TimePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'TimePickerAsset',
        ],
    ],
    'dosamigos\\multiselect\\MultiSelectAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap4\\BootstrapPluginAsset',
            'MultiSelectAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\LanguagePluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'LanguagePluginAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\ScanPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'lajax\\translatemanager\\bundles\\TranslationPluginAsset',
            'ScanPluginAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\TranslationPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'lajax\\translatemanager\\bundles\\LanguageItemPluginAsset',
            'TranslationPluginAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\LanguageAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'LanguageAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\FrontendTranslationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'FrontendTranslationAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\FrontendTranslationPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\jui\\JuiAsset',
            'lajax\\translatemanager\\bundles\\TranslationPluginAsset',
            'FrontendTranslationPluginAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\TranslateAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'TranslateAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\TranslateManagerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'TranslateManagerAsset',
        ],
    ],
    'lajax\\translatemanager\\bundles\\TranslatePluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'lajax\\translatemanager\\bundles\\TranslationPluginAsset',
            'TranslatePluginAsset',
        ],
    ],
    'frontend\\assets\\overridden\\LajaxLanguageItemPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'LajaxLanguageItemPluginAsset',
        ],
    ],
    'dosamigos\\datetimepicker\\DateTimePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\groups\\BootstrapGroupAsset',
            'DateTimePickerAsset',
        ],
    ],
    'yii\\widgets\\MaskedInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'MaskedInputAsset',
        ],
    ],
    'frontend\\assets\\WebAudioRecorder' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'WebAudioRecorder',
        ],
    ],
    'frontend\\assets\\WebPhoneAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap4\\BootstrapAsset',
            'frontend\\assets\\TwilioAsset',
            'WebPhoneAsset',
        ],
    ],
];