<?php

namespace modules\flight\src\useCases\api\voluntaryRefundCreate;

use yii\base\Model;

class TicketsForm extends Model
{
    public $number;

    public $airlinePenalty;

    public $processingFee;

    public $refundAmount;

    public function rules(): array
    {
        return [
            [['number', 'airlinePenalty', 'processingFee', 'refundAmount'], 'required'],
            [['number'], 'string', 'max' => 50],
            [['airlinePenalty', 'processingFee', 'refundAmount'], 'number']
        ];
    }

    public function load($data, $formName = null)
    {
        return parent::load($data, $formName);
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }

    public function formName()
    {
        return '';
    }
}
