<?php

namespace modules\flight\src\useCases\api\voluntaryRefundCreate;

use sales\forms\CompositeForm;
use sales\forms\CompositeRecursiveForm;
use webapi\src\forms\billing\BillingInfoForm;
use webapi\src\forms\payment\PaymentRequestForm;

/**
 * Class VoluntaryRefundCreateForm
 * @package modules\flight\src\useCases\api\voluntaryRefundCreate
 *
 * @property string $booking_id
 * @property BillingInfoForm|null $billing
 * @property PaymentRequestForm|null $payment_request
 * @property VoluntaryRefundForm $refund
 */
class VoluntaryRefundCreateForm extends CompositeForm
{
    public $booking_id;

    public function load($data, $formName = null, $forms = [])
    {
        if (isset($data['billing'])) {
            $this->billing = new BillingInfoForm();
            $this->billing->setFormName('billing');
        }

        if (isset($data['payment_request'])) {
            $this->payment_request = new PaymentRequestForm();
            $this->payment_request->setFormName('payment_request');
        }

        if (isset($data['refund'])) {
            $this->refund = new VoluntaryRefundForm(count($data['refund']['tickets']) ?? 0);
        }

        return parent::load($data, $formName);
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        if (!isset($this->refund) || empty($this->refund)) {
            $this->addError('refund', 'Refund data is not provided');
        }
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }

    public function rules(): array
    {
        return [
            [['booking_id'], 'required'],
            [['booking_id'], 'string', 'max' => 10],
        ];
    }

    public function formName(): string
    {
        return '';
    }

    /**
     * @inheritDoc
     */
    protected function internalForms(): array
    {
        return ['refund', 'billing', 'payment_request'];
    }
}
