<?php

namespace sales\entities\cases;

class CasesCategoryQuery extends \yii\db\ActiveQuery
{
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    public function byKey(string $key): self
    {
        return $this->andWhere(['cc_key' => $key]);
    }
}
