<?php

namespace common\models;

use yii\db\ActiveQuery;

class ClientEmailQuery extends ActiveQuery
{
    /**
     * @param null $db
     * @return ClientEmail[]|array
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return ClientEmail|array|null
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }
}
