<?php

namespace common\models\query;

use common\models\ClientPhone;
use yii\db\ActiveQuery;

/**
 * Class ClientPhoneQuery
 */
class ClientPhoneQuery extends ActiveQuery
{
    public function notInvalid(): self
    {
        return $this->andWhere([
            'OR',
            ['is', 'type', null],
            ['<>', 'type', ClientPhone::PHONE_INVALID],
        ]);
    }

    /**
     * @param null $db
     * @return array|ClientPhone|null
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return array|ClientPhone[]
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }
}
