<?php

namespace common\models\query;

use common\models\Conference;

/**
 * This is the ActiveQuery class for [[Conference]].
 *
 * @see Conference
 */
class ConferenceQuery extends \yii\db\ActiveQuery
{
    public function bySid(string $sid): self
    {
        return $this->andWhere(['cf_sid' => $sid]);
    }

    public function active(): self
    {
        return $this->andWhere(['cf_status_id' => Conference::STATUS_START]);
    }

    public function selectRecordingData(): self
    {
        return $this->select(['cf_recording_sid', 'cf_recording_duration']);
    }

    /**
     * @param null $db
     * @return Conference|array|null
     */
    public function one($db = null)
    {
        return parent::one($db);
    }

    /**
     * @param null $db
     * @return Conference[]|array
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }
}
