<?php

namespace common\models\query;

use common\models\Project;
use yii\db\ActiveQuery;

/**
 * Class ProjectQuery
 *
 * @see Project
 */
class ProjectQuery extends ActiveQuery
{
    public function active(): self
    {
        return $this->andWhere(['closed' => false]);
    }

    public function byName(string $name): self
    {
        return $this->andWhere(['name' => $name]);
    }

    public function byKey(string $key): self
    {
        return $this->andWhere(['project_key' => $key]);
    }

    /**
     * @param null $db
     * @return Project|array|null
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return Project[]|array
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }
}
