<?php

namespace common\models\query;

use common\models\UserOnline;

/**
 * @see UserOnline
 */
class UserOnlineQuery extends \yii\db\ActiveQuery
{
    /**
     * @param null $db
     * @return UserOnline[]|array
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return UserOnline|array|null
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }
}
