<?php

namespace modules\product\src\entities\productQuote;

/**
 * @see ProductQuote
 */
class Scopes extends \yii\db\ActiveQuery
{
    /**
     * @param null $db
     * @return array|ProductQuote|null
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return array|ProductQuote[]
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }
}
