<?php

namespace modules\product\src\entities\productQuote;

/**
 * @see ProductQuote
 */
class Scopes extends \yii\db\ActiveQuery
{
    public function byOrderId(int $orderId): self
    {
        return $this->andWhere(['pq_order_id' => $orderId]);
    }

    public function applied(): self
    {
        return $this->andWhere(['pq_status_id' => ProductQuoteStatus::APPLIED]);
    }

    public function booked(): self
    {
        return $this->andWhere(['pq_status_id' => ProductQuoteStatus::BOOKED]);
    }

    /**
     * @param null $db
     * @return array|ProductQuote|null
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return array|ProductQuote[]
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }
}
