---
- name: Configure pam limits
  pam_limits:
    domain: '*'
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - {name: 'nproc', type: 'soft', value: '200000'}
    - {name: 'nproc', type: 'hard', value: '200000'}
    - {name: 'nofile', type: 'soft', value: '200000'}
    - {name: 'nofile', type: 'hard', value: '200000'}

- name: Increase tcp_max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 65000
    sysctl_set: true
    state: present
    reload: true
    ignoreerrors: true

- name: Increase maximum number of backlogged sockets
  sysctl:
    name: net.core.somaxconn
    value: '65000'
    sysctl_set: true
    state: present
    reload: true
    ignoreerrors: true

- name: Increase maximum number of open files
  sysctl:
    name: fs.file-max
    value: '200000'
    sysctl_set: true
    state: present
    reload: true
    ignoreerrors: true
