version: '3.9'

services:
  redis:
    container_name: crm-redis
    build:
      context: ./redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    restart: on-failure
    ports:
      - ${REDIS_HOST_PORT}:6379
    networks:
      - backend

  mysql:
    container_name: crm-mysql
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_IMAGE: ${MYSQL_IMAGE}
    volumes:
      - ${MYSQL_HOST_PATH_DB}:/var/lib/mysql
      - ${MYSQL_HOST_PATH_DUMP}:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_HOST_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    security_opt:
      - seccomp:unconfined
    restart: on-failure
    networks:
      - backend

  psql:
    container_name: crm-psql
    build:
      context: ./psql
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_HOST_PATH_DB}:/var/lib/postgresql/data
      - ${POSTGRES_HOST_PATH_DUMP}:/dump
      - ${POSTGRES_HOST_PATH_DUMP}:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    restart: on-failure
    networks:
      - backend

  centrifugo:
    container_name: crm-centrifugo
    image: centrifugo/centrifugo:${CENTRIFUGO_VERSION}
    volumes:
      - ${CENTRIFUGO_CONFIG_PATH}:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - ${CENTRIFUGO_HOST_PORT}:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      backend:
      default:
        aliases:
          - centrifugo
    restart: on-failure

  beanstalkd:
    container_name: crm-beanstalkd
    build:
      context: ./beanstalkd
      args:
        version: ${BEANSTALKD_VERSION}
    restart: on-failure
    ports:
      - ${BEANSTALKD_PORT}
    networks:
      - backend

  frontend:
    container_name: crm-frontend
    build:
      context: ./frontend
      args:
        REGISTRY: ${REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
        PHP_IDE_CONFIG_WEB: ${PHP_IDE_CONFIG_WEB}
        PHP_XDEBUG_ENABLED: ${PHP_XDEBUG_ENABLED}
        XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
        XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY}
    volumes:
      - ${APP_PATH}:${APP_PATH}
    working_dir: ${APP_PATH}
    depends_on:
     - mysql
     - psql
     - redis
     - beanstalkd
     - centrifugo
     - queue
    restart: on-failure
    networks:
      - backend
      - kivork-proxy

  api:
    container_name: crm-api
    build:
      context: ./api
      args:
        REGISTRY: ${REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
        PHP_IDE_CONFIG_API: ${PHP_IDE_CONFIG_API}
    volumes:
      - ${APP_PATH}:${APP_PATH}
    working_dir: ${APP_PATH}
    depends_on:
     - mysql
     - psql
     - redis
     - beanstalkd
     - centrifugo
     - queue
    restart: on-failure
    networks:
      - backend
      - kivork-proxy

  nginx-crm:
    container_name: crm-nginx
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    volumes:
      - ${LOGS_PATH}:${LOGS_PATH}
      - ${LOGS_PATH}:/var/log/nginx
      - ${SSL_PATH}:${SSL_PATH}
      - ${FILE_STORAGE_PATH}:${FILE_STORAGE_PATH}
      - ${APP_PATH}:${APP_PATH}
    ports:
      - ${HOST_PORT}:${HOST_PORT} #frontend
      - ${HOST_API_PORT}:${HOST_API_PORT} #api
    depends_on:
      - frontend
      - api
    restart: on-failure
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=${NGINX_TEMPLATE_PATH}
      - APP_PATH=${APP_PATH}
      - LOGS_PATH=${LOGS_PATH}
      - FILE_STORAGE_PATH=${FILE_STORAGE_PATH}
      - HOST=${HOST}
      - HOST_PORT=${HOST_PORT}
      - HOST_API=${HOST_API}
      - HOST_API_PORT=${HOST_API_PORT}
      - SSL_CRT_PATH=${SSL_CRT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - WEB_SOCKET_SERVER_PORT=${WEB_SOCKET_SERVER_PORT}
      - VOIP_RECORDS_PROXY_URL=${VOIP_RECORDS_PROXY_URL}
    networks:
      - frontend
      - backend
      - kivork-proxy

  ws:
    container_name: crm-ws
    build:
      context: ./ws
      args:
        REGISTRY: ${REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ${APP_PATH}:${APP_PATH}
    working_dir: ${APP_PATH}
    depends_on:
      - mysql
      - psql
      - redis
      - beanstalkd
    restart: on-failure
    command: ./yii websocket-server-v3/start
    networks:
      - backend

  queue:
    container_name: crm-queue
    build:
      context: ./queue
      args:
        APP_PATH: ${APP_PATH}
        REGISTRY: ${REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ${APP_PATH}:${APP_PATH}
    working_dir: ${APP_PATH}
    depends_on:
      - mysql
      - psql
      - beanstalkd
      - centrifugo
      - redis
    restart: on-failure
    networks:
      - backend
      - kivork-proxy

  console:
    container_name: crm-console
    build:
      context: ./console
      args:
        REGISTRY: ${REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_ID}
        USER_GID: ${USER_GID}
    volumes:
      - ${APP_PATH}:${APP_PATH}
      - ${SSH_DIR}:/home/${USER_NAME}/.ssh
      - ${COMPOSER_CACHE_DIR}:/home/${USER_NAME}/.composer/cache
    working_dir: ${APP_PATH}
    depends_on:
      - mysql
      - psql
      - beanstalkd
      - redis
    networks:
      - backend
      - kivork-proxy

networks:
  frontend:
  backend:
  kivork-proxy:
    external: true
    name: kivork-proxy