version: '2'
services:
    nginx:
        build: ./docker/nginx
        container_name: nginx
        hostname: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/sale
    php:
        build: ./docker/php
        container_name: php
        hostname: php
        restart: unless-stopped
        volumes:
            - ./:/var/www/sale
    mysql:
        container_name: mysql
        hostname: mysql
        restart: unless-stopped
        image: mysql:5.7
        volumes:
        - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: uls_server_/*-+x
            MYSQL_DATABASE: cpanel_db
            MYSQL_USER: cpanel
            MYSQL_PASSWORD: Ltsvc06.03
volumes:
    mysql_data:
        driver: "local"