window.phoneWidget = {};
window.phoneWidget.device = {};
window.phoneWidget.device.status = {};
window.phoneWidget.device.initialize = {};
window.phoneWidget.storage = {};
window.phoneWidget.emptyFunc = function (param) {};
window.TwilioDevice = null;
window.isTwilioDevicePage = false;
window.TwilioCall = null;