---
plugin: aws_ec2
# uncomment this to run localy
#boto_profile: aws-prod-infra
cache: no
regions:
  - us-east-1
filters:
  tag:Env:
    - prod
  tag:Project:
    - crm
  tag:Ns:
    - kiv
  instance-state-name : running
keyed_groups:
  - prefix: ''
    separator: ''
    key: tags['Kind']

compose:
  ansible_host: public_ip_address
  private_ip: private_ip_address

hostnames:
  - tag:Name
