version: '3.7'

services:
    php:
        container_name: yii-php
        image: yiisoftware/yii2-php:7.4-fpm
        working_dir: /app
        volumes:
            - ../../:/app
    nginx:
        image: nginx:1.18.0-alpine
        container_name: yii-nginx
        ports:
            - 8082:80
            - 8081:81
 #           - 444:443
        volumes:
            - ../../:/app
            - ../data/nginx/:/etc/nginx/conf.d/
  #          - ./data/ssl/:/etc/nginx/ssl/
        depends_on:
            - php
        restart: always

    mysql:
        container_name: mysql
        image: mysql:8.0.26
        environment:
            - MYSQL_ROOT_PASSWORD=Password123!
            - MYSQL_DATABASE=crm-local
            - MYSQL_USER=crm_user
            - MYSQL_PASSWORD=Password123!

    pgsql:
        container_name: pgsql
        image: postgres:13-alpine
        environment:
        - POSTGRES_DB=crm
        - POSTGRES_USER=crm_user
        - POSTGRES_PASSWORD=Password123!

    redis:
        image: "redis:alpine"
        ports:
            - 6380:6379


#beanstalkd:
#    container_name: bookair_beanstalkd
#    image: schickling/beanstalkd:latest
#    restart: always
#    volumes:
#        - "./shared/beanstalkd/logs:/var/beanstalkd"
#    ports:
#        - "11300:11300"
#    networks:
#        - default