---
galaxy_info:
  author: kivork
  description: Haproxy Exporter
  license: gplv2
  company: kivork
  min_ansible_version: 2.7
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - stretch
        - buster
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - monitoring

dependencies: []
