<?php

namespace modules\order\src\forms\api\create;

use common\models\Project;
use modules\offer\src\entities\offer\Offer;
use sales\forms\CompositeRecursiveForm;

/**
 * Class OrderCreateForm
 * @package modules\order\src\forms\api
 *
 * @property string $offerGid
 * @property string $projectApiKey
 * @property ProductQuotesForm[] $productQuotes
 * @property PaymentForm $payment
 * @property BillingInfoForm $billingInfo
 * @property CreditCardForm $creditCard
 * @property TipsForm $tips
 * @property PaxesForm[] $paxes
 */
class OrderCreateForm extends CompositeRecursiveForm
{
    public string $offerGid = '';


    public function __construct($config = [])
    {
        $this->payment = new PaymentForm();
        $this->billingInfo = new BillingInfoForm();
        $this->creditCard = new CreditCardForm();
        $this->tips = new TipsForm();

        parent::__construct($config);
    }

    public function load($data, $formName = null, $forms = [])
    {
        if (!empty($data['productQuotes']) && is_array($data['productQuotes'])) {
            $productQuotesForm = [];
            for ($i = 1, $iMax = count($data['productQuotes']); $i <= $iMax; $i++) {
                $productQuotesForm[] = new ProductQuotesForm();
            }
            $this->productQuotes = $productQuotesForm;
        }

        if (!empty($data['paxes']) && is_array($data['paxes'])) {
            $paxesForm = [];
            for ($i = 1, $iMax = count($data['paxes']); $i <= $iMax; $i++) {
                $paxesForm[] = new PaxesForm();
            }
            $this->paxes = $paxesForm;
        }

        return parent::load($data, $formName, $forms); // TODO: Change the autogenerated stub
    }

    public function rules(): array
    {
        return [
            [['offerGid'], 'required'],
            [['offerGid'], 'string'],
            ['offerGid', 'exist', 'targetClass' => Offer::class, 'targetAttribute' => 'of_gid'],
        ];
    }

    public function validate($attributeNames = null, $clearErrors = true): bool
    {
        if (!isset($this->productQuotes) || empty($this->productQuotes)) {
            $this->addError('productQuotes', 'Product quotes not provided');
            return false;
        }

        if (!isset($this->paxes) || empty($this->paxes)) {
            $this->addError('paxes', 'Paxes not provided');
            return false;
        }

        return parent::validate($attributeNames, $clearErrors);
    }

    public function formName(): string
    {
        return '';
    }

    /**
     * @inheritDoc
     */
    protected function internalForms(): array
    {
        return ['productQuotes', 'payment', 'billingInfo', 'creditCard', 'tips', 'paxes'];
    }
}
