---
# This playbook provisions CRM shared server

- name: Setup shared server
  hosts: clickhouse
  remote_user: ubuntu
  gather_facts: false
  roles:
    - role: common
      tags: common
      become: true

    - role: clickhouse
      tags: clickhouse
      become: true

    - role: filebeat
      tags: filebeat
      become: true

    - role: node_exporter
      tags: node-exporter
      become: true

    - role: beat_exporter
      tags: beat-exporter
      become: true
