---
- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: true

- name: Install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip

- name: Install docker pip
  pip:
    name: docker

- name: Ensure docker is started
  service:
    name: docker
    state: started
    enabled: true

- name: Check docker-compose
  stat:
    path: /usr/local/bin/docker-compose
  register: docker_compose

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755
  when: not docker_compose.stat.exists

- name: Add ubuntu user to the docker group
  user:
    name: ubuntu
    groups:
      - docker
    append: true
