<?php
namespace modules\order\src\forms;

use modules\order\src\entities\orderTipsUserProfit\OrderTipsUserProfit;
use sales\forms\CompositeForm;

class OrderTipsUserProfitFormComposite extends CompositeForm
{
	/**
	 * OrderTipsUserProfitFormComposite constructor.
	 * @param array $orderTipsUserProfits
	 * @param int $countOrderTipsUserProfits
	 * @param array $config
	 */
	public function __construct(array $orderTipsUserProfits, int $countOrderTipsUserProfits, $config = [])
	{
		if ($countOrderTipsUserProfits) {
			$cnt = $countOrderTipsUserProfits;
		} else {
			$cnt = count($orderTipsUserProfits) ?: 1;
		}
		$orderTipsUserProfitsResult = [];
		for($i = 0; $i < $cnt; $i++) {
			if (isset($orderTipsUserProfits[$i])) {
				$orderTipsUserProfitsResult[] = $orderTipsUserProfits[$i];
			} else {
				$orderTipsUserProfitsResult[] = new OrderTipsUserProfit();
			}
		}
		$this->orderTipsUserProfits = $orderTipsUserProfitsResult;
		parent::__construct($config);
	}

	/**
	 * @inheritDoc
	 */
	protected function internalForms(): array
	{
		return ['orderTipsUserProfits'];
	}

	public function getAttributeValueByName(string $attribute)
	{
		return $this->$attribute ?? null;
	}

	public function validate($attributeNames = null, $clearErrors = true): bool
	{
		$orderTipsUserProfits = $this->getAttributeValueByName('orderTipsUserProfits');
		$sum = array_column($orderTipsUserProfits, 'otup_percent');

		if (array_sum($sum) > OrderTipsUserProfit::MAX_PERCENT) {
			$this->addError('orderTipsUserProfits.0.oup_user_id', 'Total sum of percent on this order cant be more then 100%');
			return false;
		}

		return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
	}
}