<?php

/**
 * Created by PhpStorm.
 * User: shakarim
 * Date: 6/30/22
 * Time: 2:14 PM
 */

namespace src\model\callLog\abac;

use yii\base\ActionFilter;
use yii\di\Instance;
use yii\web\ForbiddenHttpException;
use yii\web\User;

/**
 * Class CallLogAccessControl
 * @package src\model\callLog\abac
 */
class CallLogAccessControl extends ActionFilter
{
    protected $ruleConfig = [
        'class' => 'src\model\callLog\abac\CallLogAccessRule'
    ];
    public $rules;
    public $user = 'user';

    /**
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {
        parent::init();
        if ($this->user !== false) {
            $this->user = Instance::ensure($this->user, User::class);
        }
        foreach ($this->rules as $i => $rule) {
            if (is_array($rule)) {
                $this->rules[$i] = \Yii::createObject(array_merge($this->ruleConfig, $rule));
            }
        }
    }

    /**
     * @param \yii\base\Action $action
     * @return bool
     * @throws ForbiddenHttpException
     */
    public function beforeAction($action)
    {
        if (!parent::beforeAction($action)) {
            return false;
        }

        /** @var \src\model\callLog\abac\CallLogAccessRule $rule */
        $rule = isset($this->rules[$action->id]) ? $this->rules[$action->id] : null;
        if ($rule instanceof $this->ruleConfig['class'] && !$rule->isAllow($this->user)) {
            throw new ForbiddenHttpException('You\'re not allowed to this page');
        }

        return true; // TODO: Change the autogenerated stub
    }
}
