---
- name: Install ondrej/php repo
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    filename: php
    update_cache: true
  become: true

- name: Install php8.0-fpm
  apt:
    install_recommends: false
    pkg:
      - php-pear
      - php8.0
      - php8.0-cli
      - php8.0-common
      - php8.0-dev
      - php8.0-fpm
      - php8.0-bcmath
      - php8.0-curl
      - php8.0-gd
      - php8.0-igbinary
      - php8.0-imagick
      - php8.0-imap
      - php8.0-intl
      - php8.0-mbstring
      - php8.0-memcache
      - php8.0-memcached
      - php8.0-msgpack
      - php8.0-mysql
      - php8.0-opcache
      - php8.0-pgsql
      - php8.0-pspell
      - php8.0-readline
      - php8.0-redis
      - php8.0-soap
      - php8.0-sqlite3
      - php8.0-ssh2
      - php8.0-tidy
      - php8.0-xml
      - php8.0-xmlrpc
      - php8.0-zip

- name: Install Swoole
  import_tasks: swoole.yml

- name: Configure php-cli
  copy:
    src: php-cli.ini
    dest: /etc/php/8.0/cli/php.ini
    mode: 0644

- name: Configure php-fpm
  copy:
    src: php-fpm.ini
    dest: /etc/php/8.0/fpm/php.ini
    mode: 0644
  notify: restart php8.0-fpm

- name: Configure fpm pool
  template:
    src: www.conf.j2
    dest: /etc/php/8.0/fpm/pool.d/www.conf
    mode: 0644
  notify: restart php8.0-fpm

- name: Ensure php8.0-fpm is started
  service:
    name: php8.0-fpm
    state: started
    enabled: true
