---
- name: Install ondrej/php repo
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    filename: php
    update_cache: true
  become: true

- name: Install php7.4-fpm
  apt:
    pkg:
      - php-pear
      - php7.4
      - php7.4-cli
      - php7.4-common
      - php7.4-dev
      - php7.4-fpm
      - php7.4-bcmath
      - php7.4-curl
      - php7.4-gd
      - php7.4-geoip
      - php7.4-igbinary
      - php7.4-imagick
      - php7.4-imap
      - php7.4-intl
      - php7.4-json
      - php7.4-mbstring
      - php7.4-memcache
      - php7.4-memcached
      - php7.4-msgpack
      - php7.4-mysql
      - php7.4-opcache
      - php7.4-pgsql
      - php7.4-pspell
      - php7.4-readline
      - php7.4-redis
      - php7.4-soap
      - php7.4-sqlite3
      - php7.4-ssh2
      - php7.4-tidy
      - php7.4-xml
      - php7.4-xmlrpc
      - php7.4-zip

- name: Install Swoole
  import_tasks: swoole.yml

- name: Configure php-cli
  copy:
    src: php-cli.ini
    dest: /etc/php/7.4/cli/php.ini
    mode: 0644

- name: Configure php-fpm
  copy:
    src: php-fpm.ini
    dest: /etc/php/7.4/fpm/php.ini
    mode: 0644
  notify: restart php7.4-fpm

- name: Configure fpm pool
  template:
    src: www.conf.j2
    dest: /etc/php/7.4/fpm/pool.d/www.conf
    mode: 0644
  notify: restart php7.4-fpm

- name: Ensure php7.4-fpm is started
  service:
    name: php7.4-fpm
    state: started
    enabled: true
