---
- name: Install ondrej/php repo
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    filename: php
    update_cache: true
  become: true

- name: Install php8.1-fpm
  apt:
    install_recommends: false
    pkg:
      - php-pear
      - php8.1
      - php8.1-cli
      - php8.1-common
      - php8.1-dev
      - php8.1-fpm
      - php8.1-bcmath
      - php8.1-curl
      - php8.1-gd
      - php8.1-igbinary
      - php8.1-imagick
      - php8.1-imap
      - php8.1-intl
      - php8.1-mbstring
      - php8.1-memcache
      - php8.1-memcached
      - php8.1-msgpack
      - php8.1-mysql
      - php8.1-opcache
      - php8.1-pgsql
      - php8.1-pspell
      - php8.1-readline
      - php8.1-redis
      - php8.1-soap
      - php8.1-sqlite3
      - php8.1-ssh2
      - php8.1-tidy
      - php8.1-xml
      - php8.1-xmlrpc
      - php8.1-zip

- name: Install Swoole
  import_tasks: swoole.yml

- name: Configure php-cli
  copy:
    src: php-cli.ini
    dest: /etc/php/8.1/cli/php.ini
    mode: 0644

- name: Configure php-fpm
  copy:
    src: php-fpm.ini
    dest: /etc/php/8.1/fpm/php.ini
    mode: 0644
  notify: restart php8.1-fpm

- name: Configure fpm pool
  template:
    src: www.conf.j2
    dest: /etc/php/8.1/fpm/pool.d/www.conf
    mode: 0644
  notify: restart php8.1-fpm

- name: Ensure php8.1-fpm is started
  service:
    name: php8.1-fpm
    state: started
    enabled: true
