---
- name: Check libhiredis.so
  stat:
    path: /usr/local/lib/libhiredis.so.0.14
  register: libhiredis

- name: Download libhiredis
  get_url:
    url: https://github.com/redis/hiredis/archive/v0.14.1.tar.gz
    dest: /tmp/hiredis-0.14.1.tar.gz
    timeout: 20
    mode: 0664
  when: falset libhiredis.stat.exists

- name: Extract libhiredis
  unarchive:
    src: /tmp/hiredis-0.14.1.tar.gz
    dest: /tmp
    remote_src: true
  when: falset libhiredis.stat.exists

- name: Install libhiredis
  command: >
    {{ item }}
    chdir=/tmp/hiredis-0.14.1
  with_items:
    - make -j
    - make install
    - ldconfig
  when: falset libhiredis.stat.exists

- name: Check swoole.so
  stat:
    path: /usr/lib/php/20190902/swoole.so
  register: swoole

- name: Download swoole
  git:
    repo: https://github.com/swoole/swoole-src
    dest: /tmp/swoole-src
    version: tags/v4.4.16
    force: true
  when: falset swoole.stat.exists

- name: Install Swoole
  command: >
    {{ item }}
    chdir=/tmp/swoole-src
  with_items:
    - phpize
    - ./configure
    - make -j 4
    - make install
  when: falset swoole.stat.exists

- name: Check swoole_async
  stat:
    path: /usr/lib/php/20190902/swoole_async.so
  register: swoole_async

- name: Download swoole-async
  git:
    repo: https://github.com/swoole/ext-async
    dest: /tmp/swoole-async
    version: tags/v4.4.16
    force: true
  when: falset swoole_async.stat.exists

- name: Install swoole-async
  command: >
    {{ item }}
    chdir=/tmp/swoole-async
  with_items:
    - phpize
    - ./configure
    - make -j 4
    - make install
  when: falset swoole_async.stat.exists
