---
- name: Check libhiredis.so
  stat:
    path: /usr/local/lib/libhiredis.so.1.0.0
  register: libhiredis

- name: Download libhiredis
  get_url:
    url: https://github.com/redis/hiredis/archive/v1.0.2.tar.gz
    dest: /tmp/hiredis-1.0.2.tar.gz
    timeout: 20
    mode: 0664
  when: not libhiredis.stat.exists

- name: Extract libhiredis
  unarchive:
    src: /tmp/hiredis-1.0.2.tar.gz
    dest: /tmp
    remote_src: true
  when: not libhiredis.stat.exists

- name: Install libhiredis
  command: >
    {{ item }}
    chdir=/tmp/hiredis-1.0.2
  with_items:
    - make -j
    - make install
    - ldconfig
  when: not libhiredis.stat.exists

- name: Check swoole.so
  stat:
    path: //usr/lib/php/20200930/swoole.so
  register: swoole

- name: Download swoole
  git:
    repo: https://github.com/swoole/swoole-src
    dest: /tmp/swoole-src
    version: tags/v4.8.9
    force: true
  when: not swoole.stat.exists

- name: Install gcc
  apt:
    pkg:
      - g++
      - g++-9
      - libstdc++-9-dev

- name: Install Swoole
  command: >
    {{ item }}
    chdir=/tmp/swoole-src
  with_items:
    - phpize
    - ./configure
    - make -j 4
    - make install
  when: not swoole.stat.exists
