<?php

namespace modules\product\src\entities\productQuoteChange;

use yii\db\ActiveQuery;

/**
 * Class Scopes
 *
 * @see ProductQuoteChange
 */
class Scopes extends ActiveQuery
{
    public function byId(int $id): self
    {
        return $this->andWhere(['pqc_id' => $id]);
    }

    public function byProductQuote(int $quoteId): self
    {
        return $this->andWhere(['pqc_pq_id' => $quoteId]);
    }

    public function byCaseId(int $id): self
    {
        return $this->andWhere(['pqc_case_id' => $id]);
    }

    public function isNotDecided(): self
    {
        return $this->andWhere(['IS', 'pqc_decision_type_id', null]);
    }

    /**
     * @param null $db
     * @return ProductQuoteChange[]|array
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return ProductQuoteChange|array|null
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }
}
