<?php

namespace sales\behaviors;

use yii\behaviors\BlameableBehavior;

class BlameableBehaviorExceptApi extends BlameableBehavior
{
	public function attach($owner)
	{
		parent::attach($owner); // TODO: Change the autogenerated stub
		$this->attributes = [];
	}

}