---
- name: Create node_exporter user
  user:
    name: node_exporter
    shell: /usr/sbin/nologin
    state: present
    system: true
    home: /
    create_home: false

- name: Create node_exporter group
  user:
    name: node_exporter
    groups: node_exporter
    append: true

- name: Check node_exporter installation
  stat:
    path: /usr/local/bin/node_exporter
  register: node_exporter

- name: Download node_exporter tarball
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.0/node_exporter-1.0.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter-1.0.0.linux-amd64.tar.gz
    mode: 0644
    owner: root
    group: root
  when: not node_exporter.stat.exists

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter-1.0.0.linux-amd64.tar.gz
    dest: /tmp
    owner: root
    group: root
    remote_src: true
    creates: /tmp/node_exporter-1.0.0.linux-amd64/node_exporter
  when: not node_exporter.stat.exists

- name: Install node_exporter
  copy:
    src: /tmp/node_exporter-1.0.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: 0755
    owner: root
    group: root
    remote_src: true
  when: not node_exporter.stat.exists

- name: Create node_exporter service
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644

- name: Ensure node_exporter is started
  systemd:
    name: node_exporter
    daemon_reload: true
    enabled: true
    state: started
