<?php

namespace src\model\clientChatRequest\useCase\api\create\query;

use common\models\Employee;
use src\model\userClientChatData\entity\UserClientChatData;
use yii\db\ActiveQuery;

/**
 * Class LeadQuery
 */
class EmployeeQuery extends ActiveQuery
{
    /**
     * @param null $db
     * @return array|Employee[]
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return array|Employee|null
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    public static function getEmployeeByUsernameClientChatData(string $username): ?Employee
    {
        return Employee::find()
            ->leftJoin(['uccd' => UserClientChatData::tableName()], 'uccd.uccd_employee_id='. Employee::tableName() .'.id')
            ->where('uccd.uccd_username=:username', [':username' => $username])
            ->limit(1)
            ->one();
    }
}
