<?php

namespace src\model\clientChatRequest\useCase\api\create\query;

use src\model\userClientChatData\entity\UserClientChatData;
use yii\db\ActiveQuery;

/**
 * Class LeadQuery
 */
class UserClientChatDataQuery extends ActiveQuery
{
    /**
     * @param null $db
     * @return array|UserClientChatData[]
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return array|UserClientChatData|null
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    public static function getUserClientChatDataByUsername(string $username): ?UserClientChatData
    {
        return UserClientChatData::find()
            ->where('uccd_username=:username', [':username' => $username])
            ->limit(1)
            ->one();
    }
}
