---
- name: Install python3-pip package
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Check stick tables exporter exists
  stat:
    path: /usr/local/bin/stick_tables_exporter.py
  register: stickexporter

- name: Copy stick tables exporter binary
  copy:
    src: "stick_tables_exporter.py"
    dest: /usr/local/bin/stick_tables_exporter.py
    mode: 0755
    owner: "{{ haproxy_exporter_user }}"
    group: "{{ haproxy_exporter_user }}"
  become: yes
  when: not stickexporter.stat.exists

- name: Install prometheus client
  pip:
    name: prometheus_client
    executable: pip3
  become: yes

- name: Create stick_tables_exporter service
  template:
    src: stick_tables_exporter.service.j2
    dest: /etc/systemd/system/stick_tables_exporter.service
    mode: 0755
  notify:
    - restart_stick_tables_exporter
  become: yes

- name: Ensure stick_tables_exporter is started and enabled on boot.
  service:
    name: stick_tables_exporter
    state: started
    enabled: yes
  become: yes
